In [87]:
#데이터프레임에서 데이터 합치기!!
#pandas의 concat 함수: 데이터프레임 합치기
import pandas as pd

In [88]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> 

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [89]:
df=pd.DataFrame({'a':['a1','a2','a3'],
             'b':['b1','b2','b3'],
             'c':['c1','c2','c3'],
             'd':['d1','d2', 'd3']},
              index=[1,2,3])
df2=pd.DataFrame({'a':['a4','a2','a3'],
             'b':['b4','b2','b3'],
             'c':['c4','c2','c3'],
             'd':['d4','d2', 'd3']},index=[4,2,3])

In [90]:
df12=pd.concat([df1,df2],axis=0)
df12

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A    B    C    D    a    b    c    d
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4
2  NaN  NaN  NaN  NaN   a2   b2   c2   d2
3  NaN  NaN  NaN  NaN   a3   b3   c3   d3

In [91]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']},
    index=[0, 1, 2])
df2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5'],
    'D': ['D3', 'D4', 'D5']},
    index=[3, 4, 5])

In [92]:
df12=pd.concat([df1,df2],axis=0)
df12

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [93]:
df3 = pd.DataFrame({'E': ['A6', 'A7', 'A8'],
    'F': ['B6', 'B7', 'B8'],
    'G': ['C6', 'C7', 'C8'],
    'H': ['D6', 'D7', 'D8']},
    index=[0, 1, 2])

In [94]:
df13_1=pd.concat([df1,df3],axis=1)
df13_1

A   B   C   D   E   F   G   H
0  A0  B0  C0  D0  A6  B6  C6  D6
1  A1  B1  C1  D1  A7  B7  C7  D7
2  A2  B2  C2  D2  A8  B8  C8  D8

In [95]:
df4 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'E': ['E0', 'E1', 'E2']},
     index=[0, 1, 3])

In [96]:
pd.concat([df1,df4],axis=0,join='outer')
#default : axis=0(위아래), join='outer'(합집합)

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
0  A0  B0  C0  NaN   E0
1  A1  B1  C1  NaN   E1
3  A2  B2  C2  NaN   E2

In [97]:
pd.concat([df1,df4],axis=0,join='inner')
#default : axis=0(위아래), join='outer'(합집합)

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A0  B0  C0
1  A1  B1  C1
3  A2  B2  C2

In [98]:
df1
df4
pd.concat([df1,df4],axis=1,join='inner',join_axes=[df1.index])
#inner조인이지만 df1은 다 나왔으면 할때! join_axes

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  This is separate from the ipykernel package so we can avoid doing imports until


A   B   C   D    A    B    C    E
0  A0  B0  C0  D0   A0   B0   C0   E0
1  A1  B1  C1  D1   A1   B1   C1   E1
2  A2  B2  C2  D2  NaN  NaN  NaN  NaN

In [99]:
df5 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'D': ['D0', 'D1', 'D2']},
     index=['r0', 'r1', 'r2'])


df6 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
     'B': ['B3', 'B4', 'B5'],
     'C': ['C3', 'C4', 'C5'],
     'D': ['D3', 'D4', 'D5']},
     index=['r3', 'r4', 'r5'])

In [100]:
pd.concat([df5,df6],axis=0)

A   B   C   D
r0  A0  B0  C0  D0
r1  A1  B1  C1  D1
r2  A2  B2  C2  D2
r3  A3  B3  C3  D3
r4  A4  B4  C4  D4
r5  A5  B5  C5  D5

In [101]:
pd.concat([df5,df6],axis=0,ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [102]:
pd.concat([df5,df6],axis=1,ignore_index=True)

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2    3    4    5    6    7
r0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
r1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
r2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
r3  NaN  NaN  NaN  NaN   A3   B3   C3   D3
r4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
r5  NaN  NaN  NaN  NaN   A5   B5   C5   D5

In [103]:
df56_keys=pd.concat([df5,df6],axis=0, keys=['df_5','df_6'])
#keys : 계층적으로 index를 생성

In [104]:
df56_keys.ix['df_5'][1:2]

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A   B   C   D
r1  A1  B1  C1  D1

In [105]:
df56_keys.ix['df_6'][0:1]

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A   B   C   D
r3  A3  B3  C3  D3

In [106]:
df56_keys=pd.concat([df5,df6],axis=0, keys=['df_5','df_6'],names=['dfName','rowData'])
#keys : 계층적으로 index를 생성
df56_keys

A   B   C   D
dfName rowData                
df_5   r0       A0  B0  C0  D0
       r1       A1  B1  C1  D1
       r2       A2  B2  C2  D2
df_6   r3       A3  B3  C3  D3
       r4       A4  B4  C4  D4
       r5       A5  B5  C5  D5

In [107]:
#verify_integrity:index 중복 여부 확인
#default:False
#True로 설정하게 되면, index 중복시 에러 발생

In [108]:
df7 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
     'B': ['B0', 'B1', 'B2'],
     'C': ['C0', 'C1', 'C2'],
     'D': ['D0', 'D1', 'D2']},
     index=['r0', 'r1', 'r2'])

df8 = pd.DataFrame({'A': ['A2', 'A3', 'A4'],
     'B': ['B2', 'B3', 'B4'],
     'C': ['C2', 'C3', 'C4'],
     'D': ['D2', 'D3', 'D4']},
     index=['r2', 'r3', 'r4'])

In [109]:
pd.concat([df7,df8],verify_integrity=True)

ValueError: Indexes have overlapping values: Index(['r2'], dtype='object')

In [110]:
#concat함수, append함수 : 데이터프레임과 시리즈간 합치기
from pandas import DataFrame
from pandas import Series

In [111]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']},
    index=[0, 1, 2])

In [112]:
type(df1)
type(df1['A']) #df1.A
#type(df1[['A','B']])

pandas.core.series.Series

In [113]:
S1=pd.Series(['s1','s2','s3'],name="S")
S1

0    s1
1    s2
2    s3
Name: S, dtype: object

In [114]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [115]:
pd.concat([df1,S1],axis=1)

A   B   C   D   S
0  A0  B0  C0  D0  s1
1  A1  B1  C1  D1  s2
2  A2  B2  C2  D2  s3

In [116]:
pd.concat([df1,S1],axis=1,ignore_index=True)

0   1   2   3   4
0  A0  B0  C0  D0  s1
1  A1  B1  C1  D1  s2
2  A2  B2  C2  D2  s3

In [117]:
S1=pd.Series(['s1','s2','s3'],name='S')
S2=pd.Series([1,2,3])
S3=pd.Series([4,5,6])
S3
pd.concat([S1,S2,S3],axis=1)

S  0  1
0  s1  1  4
1  s2  2  5
2  s3  3  6

In [118]:
#merge:빠름 concat보다, sql명령문과 비슷
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key 

In [119]:
dfleft = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']})


dfright = DataFrame({'KEY': ['K2', 'K3', 'K4', 'K5'],
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']})


In [120]:
#dfleft,dfright를 key변수를 기준으로 merge
pd.merge(dfleft,dfright,how="outer")
#defalult = inner

KEY    A    B    C    D
0  K0   A0   B0  NaN  NaN
1  K1   A1   B1  NaN  NaN
2  K2   A2   B2   C2   D2
3  K3   A3   B3   C3   D3
4  K4  NaN  NaN   C4   D4
5  K5  NaN  NaN   C5   D5

In [121]:
pd.merge(dfleft,dfright,how="inner")

KEY   A   B   C   D
0  K2  A2  B2  C2  D2
1  K3  A3  B3  C3  D3

In [122]:
#pd.merge(dfleft,dfright,how="right")
print(dfleft)
print(dfright)
print(pd.merge(dfleft,dfright,how="left",on='KEY'))

  KEY   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
  KEY   C   D
0  K2  C2  D2
1  K3  C3  D3
2  K4  C4  D4
3  K5  C5  D5
  KEY   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1  NaN  NaN
2  K2  A2  B2   C2   D2
3  K3  A3  B3   C3   D3


In [123]:
print(pd.merge(dfleft,dfright,how="right",on='KEY'))

  KEY    A    B   C   D
0  K2   A2   B2  C2  D2
1  K3   A3   B3  C3  D3
2  K4  NaN  NaN  C4  D4
3  K5  NaN  NaN  C5  D5


In [124]:
pd.merge(dfleft,dfright,how='outer',on='KEY')

KEY    A    B    C    D
0  K0   A0   B0  NaN  NaN
1  K1   A1   B1  NaN  NaN
2  K2   A2   B2   C2   D2
3  K3   A3   B3   C3   D3
4  K4  NaN  NaN   C4   D4
5  K5  NaN  NaN   C5   D5

In [125]:
pd.merge(dfleft,dfright,how='outer',on='KEY',indicator=True)

KEY    A    B    C    D      _merge
0  K0   A0   B0  NaN  NaN   left_only
1  K1   A1   B1  NaN  NaN   left_only
2  K2   A2   B2   C2   D2        both
3  K3   A3   B3   C3   D3        both
4  K4  NaN  NaN   C4   D4  right_only
5  K5  NaN  NaN   C5   D5  right_only

In [59]:
pd.merge(dfleft,dfright,how='outer',on='KEY',indicator='indicator_info')

KEY    A    B    C    D indicator_info
0  K0   A0   B0  NaN  NaN      left_only
1  K1   A1   B1  NaN  NaN      left_only
2  K2   A2   B2   C2   D2           both
3  K3   A3   B3   C3   D3           both
4  K4  NaN  NaN   C4   D4     right_only
5  K5  NaN  NaN   C5   D5     right_only

In [60]:
dfleft2 = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
     'A': ['A0', 'A1', 'A2', 'A3'],
     'B': ['B0', 'B1', 'B2', 'B3'],
     'C': ['C0', 'C1', 'C2', 'C3']})

dfright_2 = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
     'B': ['B0_2', 'B1_2', 'B2_2', 'B3_2'],
     'C': ['C0_2', 'C1_2', 'C2_2', 'C3_2'],
     'D': ['D0_2', 'D1_2', 'D2_2', 'D3_3']})

In [61]:
pd.merge(dfleft2,dfright_2,how='inner', on='KEY')
pd.merge(dfleft2,dfright_2,how='inner',on='KEY',suffixes=('_left','_right'))

KEY   A B_left C_left B_right C_right     D
0  K0  A0     B0     C0    B0_2    C0_2  D0_2
1  K1  A1     B1     C1    B1_2    C1_2  D1_2
2  K2  A2     B2     C2    B2_2    C2_2  D2_2
3  K3  A3     B3     C3    B3_2    C3_2  D3_3

In [62]:
#데이터프레임을 인덱스를 기준으로 병합

dfleft = DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']},
    index= ['K0', 'K1', 'K2', 'K3'])
dfright = DataFrame({
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']},
    index=['K2', 'K3', 'K4', 'K5'])

In [63]:
#index 기준 병합 방법 : join(), merge()
#index 기준 left join 수행

#merge()를 이용한 left join
pd.merge(dfleft,dfright, left_index=True,right_index=True)
pd.merge(dfleft,dfright, left_index=True,right_index=True, how='right')

A    B   C   D
K2   A2   B2  C2  D2
K3   A3   B3  C3  D3
K4  NaN  NaN  C4  D4
K5  NaN  NaN  C5  D5

In [64]:
pd.merge(dfleft,dfright, left_index=True,right_index=True, how='right')
#merge함수는 판다스가 가지고 있지만 join함수는 데이터프레임이
dfleft.join(dfright) #how=left
dfleft.join(dfright, how='right')

A    B   C   D
K2   A2   B2  C2  D2
K3   A3   B3  C3  D3
K4  NaN  NaN  C4  D4
K5  NaN  NaN  C5  D5

In [65]:
dfleft = DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']},
    index= ['K0', 'K1', 'K2', 'K3'])
dfright = DataFrame({
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']},
    index=['K2', 'K3', 'K4', 'K5'])

In [66]:
#index기준 합치기,(merge함수 이용)
#k0
#k1
#k2
#k3

pd.merge(dfleft,dfright,left_index=True,right_index=True,how='left')
#join함수 이용 동일한 결과로
dfleft.join(dfright,how='left')
dfright.join(dfleft,how='right')
#merge함수 이용 outer join
pd.merge(dfleft,dfright,left_index=True,right_index=True,how='outer')
#join함수로 outer
dfleft.join(dfright,how='outer')

A    B    C    D
K0   A0   B0  NaN  NaN
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3   A3   B3   C3   D3
K4  NaN  NaN   C4   D4
K5  NaN  NaN   C5   D5

In [67]:
#index와 key를 조합하여 merge
dfleft = DataFrame({'KEY': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']})
dfright = DataFrame({
    'C': ['C2', 'C3', 'C4', 'C5'],
    'D': ['D2', 'D3', 'D4', 'D5']},
   index=['K2', 'K3', 'K4', 'K5'])
print(dfleft)
print(dfright)
pd.merge(dfleft,dfright,left_on='KEY',right_index=True, how='left')
dfleft.join(dfright,on='KEY',how='left')

  KEY   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
     C   D
K2  C2  D2
K3  C3  D3
K4  C4  D4
K5  C5  D5


KEY   A   B    C    D
0  K0  A0  B0  NaN  NaN
1  K1  A1  B1  NaN  NaN
2  K2  A2  B2   C2   D2
3  K3  A3  B3   C3   D3

In [185]:
#문제6
import numpy as np
inputData=[0,0,3,5,2,4,9,0,6,4,0,6,0,0]
buildData=[[0]*14]*10
buildData=np.array(buildData)
count=0
for i in range (0,14):#그저 보기 편하게
    for j in range(0,inputData[i]):
        buildData[9-j][i]=1
print(buildData)
for i in range(2,12):#가장 높은 층만 찾아서 조망권 검사
    j=0
    while True:
        print(i,inputData[i]-j,inputData[i-1],inputData[i-2],inputData[i+1],inputData[i+2])
        if (inputData[i]-j) > (inputData[i-1]) and (inputData[i]-j) > (inputData[i-2]) and (inputData[i]-j) > (inputData[i+1]) and (inputData[i]-j) > (inputData[i+2]):
            count+=1
            j+=1
        else:
            break
print(count)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 1 0 1 1 0 1 1 0 1 0 0]
 [0 0 1 1 0 1 1 0 1 1 0 1 0 0]
 [0 0 1 1 1 1 1 0 1 1 0 1 0 0]
 [0 0 1 1 1 1 1 0 1 1 0 1 0 0]]
2 3 0 0 5 2
3 5 3 0 2 4
3 4 3 0 2 4
4 2 5 3 4 9
5 4 2 5 9 0
6 9 4 2 0 6
6 8 4 2 0 6
6 7 4 2 0 6
6 6 4 2 0 6
7 0 9 4 6 4
8 6 0 9 4 0
9 4 6 0 0 6
10 0 4 6 6 0
11 6 0 4 0 0
11 5 0 4 0 0
11 4 0 4 0 0
6


In [175]:
#문제1
import pandas as pd
from pandas import DataFrame as df
concat_1=pd.read_csv("concat_1.csv")
concat_2=pd.read_csv("concat_2.csv")
concat_3=pd.read_csv("concat_3.csv")
concat_12=pd.merge(concat_1,concat_2,how='outer')
pd.merge(concat_12,concat_3,how='outer')
pd.merge(pd.merge(concat_1,concat_2,how='outer'),concat_3,how='outer')
# concat_1.join(concat_2, how='outer',rsuffix=("2"))

A    B    C    D
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [188]:
#문제5
import pandas as pd
from pandas import DataFrame as df
survey_site=pd.read_csv('survey_site.csv')
survey_visited=pd.read_csv('survey_visited.csv')
print(pd.merge(survey_site,survey_visited,left_on='name',right_on='site'))
print(pd.merge(survey_site,survey_visited,left_index=True,right_index=True,how='outer'))

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14
    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-3 -47.15 -126.72    622   DR-1  1927-02-10
2  MSK-4 -48.87 -123.40    734   DR-3  1939-01-07
3    NaN    NaN     NaN    735   DR-3  1930-01-12
4    NaN    NaN     NaN    751   DR-3  1930-02-26
5    NaN    NaN     NaN    752   DR-3         NaN
6    NaN    NaN     NaN    837  MSK-4  1932-01-14
7    NaN    NaN     NaN    844   DR-1  1932-03-22
