In [3]:
"""
정규화 : 0~1사이의 범위로 데이터를 표준화
인공신경망에서 데이터 대부분 0~1사이

5 3 1 7 9 => 0~1 =>  각데이터-1/9-1(최대값 - 최소값)
최대값은 1이되고 최소값은 0이되어버리고 나머지는 그사이...


"""
import warnings
warnings.filterwarnings(action='ignore')

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler 
#sklearn 머신러닝 관련 알고리즘 모두 있는 패키지

In [53]:
data=np.array([[10,-10,2],
               [5,0,6],
              [0,7,4]])
data


array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [56]:
data_mm=(data-data.min(axis=0))/(data.max(axis=0)-data.min(axis=0))
# data.max() #data 배열 전체에서 최대값
# data.max(axis=0)#각 열 단위 최대값
# data.max(axis=1)#각 행 단위 최대값
data_mm

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [63]:
mms=MinMaxScaler()
datamms=mms.fit_transform(data)
datamms
#? 행단위 하려면? 전체 하려면?

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [14]:
from sklearn.preprocessing import minmax_scale

In [71]:
datamm=minmax_scale(data, axis=1) 
datamm

array([[1.        , 0.        , 0.6       ],
       [0.83333333, 0.        , 1.        ],
       [0.        , 1.        , 0.57142857]])

In [ ]:
#이항변수화 : 연속형변수를 기준이하->0,기준초과->1
#확률변수 x가 이항분포를 따른다고 했을때, 
#0또는 1값을 갖는 이항변수화가 필요
#베르누이시행:어떤 실험 반복시 성공1 혹은 실패0로만 분류시행
#성공확률이 p인 베르누이시행을 n번 수행,
#성공하는 횟수를 x라고 하면,
#확률변수 x는 모수 n과 p인 이항분포를 따른다.

"""
주사위 : 3
3이 나올 확률(성공) : 1/6
실패:5/6

A,B,C,D
(A만 성공, B만 성공, C만 성공, D만 성공)
A만 성공 : 6/1 * (5/6)^3=0.09
B만 성공 : 6/1 * (5/6)^3=0.09
C만 성공 : 6/1 * (5/6)^3=0.09
D만 성공 : 6/1 * (5/6)^3=0.09
0.09*4=0.36
성공확률(p)*시나리오수(n)

"""

In [30]:
from sklearn.preprocessing import Binarizer

In [31]:
data=np.array([[10,-10,2],
               [5,0,6],
              [0,7,4]])
data


array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [32]:
bina=Binarizer(threshold=5 ).fit(data)
bina

Binarizer(copy=True, threshold=5)

In [33]:
bina.transform(data)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [106]:
from sklearn.preprocessing import binarize

In [107]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [109]:
binarize(data,threshold=5,copy=False)
#copy=True default
#copy=False이면, 원본 데이터로 binarize하기때문에 원본 변화

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#바이너라이저 : 연속형 변수를 이항변수화
#원핫인코더 : 범주형 변수를 이항변수화
"""
연령대:20대->0, 30대->1,40대->2
성별:남->0, 여->1
학점:A->0, B->1, C->2, D->3, E->4

20대 여 B => 100 01 01000
30대 남 D => 010 10 00010

학점
01234
10000(A)
01000(B)
...
00001(F)
"""

In [35]:
from sklearn.preprocessing import OneHotEncoder


In [36]:
#       [성별,연령,학점]  
data=np.array([[0,0,0],
              [0,1,1],
              [0,2,2],
              [1,0,3],
              [1,1,4],
              ])
data

array([[0, 0, 0],
       [0, 1, 1],
       [0, 2, 2],
       [1, 0, 3],
       [1, 1, 4]])

In [37]:
ohe=OneHotEncoder()
ohe.fit(data)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [40]:
ohe.active_features_
#[남,여,20,30,40,a,b,c,d,f]
ohe.n_values_
#범주 개수
ohe.feature_indices_
#성별 : 0이상 2미만,
#연령 : 2이상 5미만,
#학점 : 5이상 10미만

array([ 0,  2,  5, 10], dtype=int32)

In [44]:
#범주형 데이터 -> 이항변수화
data=np.array([[1,2,3]])#여성 40대 D학점
ohe.transform(data).toarray()

array([[0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [72]:
df = pd.DataFrame({'C1': np.random.randn(20),

   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',

   'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})
df

C1 C2
0   0.715279  a
1  -1.545400  a
2  -0.008384  a
3   0.621336  a
4  -0.720086  a
5   0.265512  a
6   0.108549  a
7   0.004291  a
8  -0.174600  a
9   0.433026  a
10  1.203037  b
11 -0.965066  b
12  1.028274  b
13  0.228630  b
14  0.445138  b
15 -1.136602  b
16  0.135137  b
17  1.484537  b
18 -1.079805  b
19 -1.977728  b

In [49]:
"""
np.digitize함수, np.where함수:연속형 변수 -> 이산화
이항변수화: 0또는 1 값을 갖는 변수를 만드는 것
이산(형)화: 연속형 변수를 2개 이상의 범주를 갖는 변수로 변환
ex)점수:75 -> A/B/C/D/F(범주=category)
"""
np.random.seed(10)#seed를 갖게 주면 같은 난수가 출력 42, 777, 1004
#모델 만드는 과정에서 난수를 많이사용(모든 데이터 사용x 그중 랜덤 일부 사용)
#여러 테스트 시, 데이터 다르지 않도록 하기 위함
np.random.randn(1)

array([1.3315865])

In [83]:
"""
df의 c1열 20개 data구성
10개 bin으로 균등하게 나눔
"""
df.C1.min() #-1.977
df.C1.max() # 1.484
bins=np.linspace(df.C1.min(), df.C1.max(),10)
bins
df.C1
df['C1_bin']=np.digitize(df['C1'],bins)
df


C1 C2  C1_bin
0   0.715279  a       8
1  -1.545400  a       2
2  -0.008384  a       6
3   0.621336  a       7
4  -0.720086  a       4
5   0.265512  a       6
6   0.108549  a       6
7   0.004291  a       6
8  -0.174600  a       5
9   0.433026  a       7
10  1.203037  b       9
11 -0.965066  b       3
12  1.028274  b       8
13  0.228630  b       6
14  0.445138  b       7
15 -1.136602  b       3
16  0.135137  b       6
17  1.484537  b      10
18 -1.079805  b       3
19 -1.977728  b       1

In [91]:
#이산형화를 왜 많이 할까?
#구간별로 요약통계, 범주간 평균 차이, 독립성 검정
#indexing...
df.groupby('C1_bin')['C1'].size()
df.groupby('C1_bin')['C1'].mean()
df.groupby('C1_bin')['C1'].std()
df.groupby('C1_bin')['C2'].value_counts()

df[df['C1_bin']==4]

C1 C2  C1_bin
4 -0.720086  a       4

In [97]:
#pd.get_dummies():가변수 생성
#겟 더미를 이용 온핫 인코딩
df.C1_bin
pd.get_dummies(df['C1_bin'],prefix='C1')
#모델=x1*가중치+x2*가중치+...+x3*가중치

C1_1  C1_2  C1_3  C1_4  C1_5  C1_6  C1_7  C1_8  C1_9  C1_10
0      0     0     0     0     0     0     0     1     0      0
1      0     1     0     0     0     0     0     0     0      0
2      0     0     0     0     0     1     0     0     0      0
3      0     0     0     0     0     0     1     0     0      0
4      0     0     0     1     0     0     0     0     0      0
5      0     0     0     0     0     1     0     0     0      0
6      0     0     0     0     0     1     0     0     0      0
7      0     0     0     0     0     1     0     0     0      0
8      0     0     0     0     1     0     0     0     0      0
9      0     0     0     0     0     0     1     0     0      0
10     0     0     0     0     0     0     0     0     1      0
11     0     0     1     0     0     0     0     0     0      0
12     0     0     0     0     0     0     0     1     0      0
13     0     0     0     0     0     1     0     0     0      0
14     0     0     0     0     0     0     1     0     0      0
15     0     0     1     0     0     0     0     0     0      0
16     0     0     0     0     0     1     0     0     0      0
17     0     0     0     0     0     0     0     0     0      1
18     0     0     1     0     0     0     0     0     0      0
19     1     0     0     0     0     0     0     0     0      0

In [105]:
#np.where(조건,참,거짓)
df["h_l"]=np.where(df['C1']>=df.C1.mean(),"high","low")
df
df.groupby("h_l")['C1'].size()
df.groupby("h_l")['C1'].mean()
df.groupby("h_l")['C1'].std()

h_l
high    0.476821
low     0.575615
Name: C1, dtype: float64

In [111]:
q1=np.percentile(df['C1'],25)
q3=np.percentile(df['C1'],75)
#연습문제:C1열 값이 <= q1 이면 df['h_m_l']=ㅣ
#C1열 값이 > q1 and <=q3 df['h_m_l']=m
#else df['h_m_l']=h
df['h_m_l']=np.where(df['C1']>=q3,'high',np.where(df['C1']>=q1,
                                                 'medium','low'))
df

C1 C2  C1_bin   h_l   h_m_l
0   0.715279  a       8  high    high
1  -1.545400  a       2   low     low
2  -0.008384  a       6  high  medium
3   0.621336  a       7  high    high
4  -0.720086  a       4   low  medium
5   0.265512  a       6  high  medium
6   0.108549  a       6  high  medium
7   0.004291  a       6  high  medium
8  -0.174600  a       5   low  medium
9   0.433026  a       7  high  medium
10  1.203037  b       9  high    high
11 -0.965066  b       3   low     low
12  1.028274  b       8  high    high
13  0.228630  b       6  high  medium
14  0.445138  b       7  high  medium
15 -1.136602  b       3   low     low
16  0.135137  b       6  high  medium
17  1.484537  b      10  high    high
18 -1.079805  b       3   low     low
19 -1.977728  b       1   low     low

In [ ]:
"""
데이터 재구조화
-피봇테이블(pivot, pivot_table) 관련함수 두가지...
-스택(stack, unstack)
-멜트(melt)
-wide_to_long, crosstab
"""

In [260]:
data = pd.DataFrame({'cust_id': ['c1', 'c1', 'c1', 'c2', 'c2', 'c2', 'c3', 'c3', 'c3'],

   'prod_cd': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
'grade' : ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],

   'pch_amt': [30, 10, 0, 40, 15, 30, 0, 0, 10]})
data

cust_id prod_cd grade  pch_amt
0      c1      p1     A       30
1      c1      p2     A       10
2      c1      p3     A        0
3      c2      p1     A       40
4      c2      p2     A       15
5      c2      p3     A       30
6      c3      p1     B        0
7      c3      p2     B        0
8      c3      p3     B       10

In [261]:
#       p1 p2 p3
# cid
# c1   30 10   0  
# c2   40 15  30
# c3    ...

#data.pivot(index='cust_id',columns='prod_cd',values='pch_amt')
pd.pivot_table(data,index='cust_id',columns='prod_cd',values='pch_amt')

# data.pivot(index=['cust_id', 'grade'],
#            columns='prod_cd',
#            values='pch_amt')
#에러

pd.pivot_table(data,index=['cust_id', 'grade'],
               columns='prod_cd',
               values='pch_amt')

pd.pivot_table(data,index='cust_id',
               columns=['grade','prod_cd'],
               values='pch_amt')

grade       A                B           
prod_cd    p1    p2    p3   p1   p2    p3
cust_id                                  
c1       30.0  10.0   0.0  NaN  NaN   NaN
c2       40.0  15.0  30.0  NaN  NaN   NaN
c3        NaN   NaN   NaN  0.0  0.0  10.0

In [126]:
#pivot_table:집계함수 제공
pd.pivot_table(data,index="grade",columns='prod_cd',values='pch_amt')
#default평균
pd.pivot_table(data,index="grade",columns='prod_cd',values='pch_amt',
               aggfunc=np.mean)
pd.pivot_table(data,index="grade",columns='prod_cd',values='pch_amt',
              aggfunc=np.sum)
data.pivot(index="grade",columns='prod_cd',)

prod_cd  p1  p2  p3
grade              
A        70  25  30
B         0   0  10

In [ ]:
#stack():위에서 아래로 쌓는것
#unstack:쌓여 있는 것을 옆으로 놓는것(왼->오)

In [131]:
mul_index = pd.MultiIndex.from_tuples([('cust_1', '2020'), ('cust_1', '2021'),

   ('cust_2', '2020'), ('cust_2', '2021')])  

mul_index

data = pd.DataFrame(data=np.arange(16).reshape(4, 4),
index=mul_index,
columns=['prd_1', 'prd_2', 'prd_3', 'prd_4'],
dtype='int')
data

prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2      3
       2021      4      5      6      7
cust_2 2020      8      9     10     11
       2021     12     13     14     15

In [132]:
datastd=data.stack()
datastd

cust_1  2020  prd_1     0
              prd_2     1
              prd_3     2
              prd_4     3
        2021  prd_1     4
              prd_2     5
              prd_3     6
              prd_4     7
cust_2  2020  prd_1     8
              prd_2     9
              prd_3    10
              prd_4    11
        2021  prd_1    12
              prd_2    13
              prd_3    14
              prd_4    15
dtype: int32

In [133]:
datastd.index

MultiIndex([('cust_1', '2020', 'prd_1'),
            ('cust_1', '2020', 'prd_2'),
            ('cust_1', '2020', 'prd_3'),
            ('cust_1', '2020', 'prd_4'),
            ('cust_1', '2021', 'prd_1'),
            ('cust_1', '2021', 'prd_2'),
            ('cust_1', '2021', 'prd_3'),
            ('cust_1', '2021', 'prd_4'),
            ('cust_2', '2020', 'prd_1'),
            ('cust_2', '2020', 'prd_2'),
            ('cust_2', '2020', 'prd_3'),
            ('cust_2', '2020', 'prd_4'),
            ('cust_2', '2021', 'prd_1'),
            ('cust_2', '2021', 'prd_2'),
            ('cust_2', '2021', 'prd_3'),
            ('cust_2', '2021', 'prd_4')],
           )

In [139]:
datastd['cust_2']['2020']['prd_1']
datastd['cust_2']['2020'][['prd_1','prd_2']]

prd_1    8
prd_2    9
dtype: int32

In [153]:
data.ix['cust_2','prd_4']=np.nan
data

prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2    3.0
       2021      4      5      6    7.0
cust_2 2020      8      9     10    NaN
       2021     12     13     14    NaN

In [155]:
data.stack()
#nan은 출력이 되지 않음
data.stack(dropna=False)#디폴트로 nan 출력 안됨

cust_1  2020  prd_1     0.0
              prd_2     1.0
              prd_3     2.0
              prd_4     3.0
        2021  prd_1     4.0
              prd_2     5.0
              prd_3     6.0
              prd_4     7.0
cust_2  2020  prd_1     8.0
              prd_2     9.0
              prd_3    10.0
              prd_4     NaN
        2021  prd_1    12.0
              prd_2    13.0
              prd_3    14.0
              prd_4     NaN
dtype: float64

In [158]:
data = pd.DataFrame({'cust_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],
   'prd_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],
   'pch_cnt' : [1, 2, 3, 4],
'pch_amt' : [100, 200, 300, 400]})
data

cust_ID prd_CD  pch_cnt  pch_amt
0   C_001  P_001        1      100
1   C_001  P_002        2      200
2   C_002  P_001        3      300
3   C_002  P_002        4      400

In [160]:
pd.melt(data,id_vars=['cust_ID','prd_CD'])
pd.melt(data,id_vars=['cust_ID','prd_CD'],var_name='CD', value_name='VAL')

cust_ID prd_CD       CD  VAL
0   C_001  P_001  pch_cnt    1
1   C_001  P_002  pch_cnt    2
2   C_002  P_001  pch_cnt    3
3   C_002  P_002  pch_cnt    4
4   C_001  P_001  pch_amt  100
5   C_001  P_002  pch_amt  200
6   C_002  P_001  pch_amt  300
7   C_002  P_002  pch_amt  400

In [174]:
pew=pd.read_csv("C:/Users\student/Downloads/Python_JP/data/pew.csv")
pew.head()#head 앞에 5개
pew.iloc[:,0:6]

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k
0                  Agnostic     27       34       60       81       76
1                   Atheist     12       27       37       52       35
2                  Buddhist     27       21       30       34       33
3                  Catholic    418      617      732      670      638
4        Don’t know/refused     15       14       15       11       10
5          Evangelical Prot    575      869     1064      982      881
6                     Hindu      1        9        7        9       11
7   Historically Black Prot    228      244      236      238      197
8         Jehovah's Witness     20       27       24       24       21
9                    Jewish     19       19       25       25       30
10            Mainline Prot    289      495      619      655      651
11                   Mormon     29       40       48       51       56
12                   Muslim      6        7        9       10        9
13                 Orthodox     13       17       23       32       32
14          Other Christian      9        7       11       13       13
15             Other Faiths     20       33       40       46       49
16    Other World Religions      5        2        3        4        2
17             Unaffiliated    217      299      374      365      341

In [178]:
pd.melt(pew,id_vars=['religion'],var_name='income',value_name='count')

religion              income  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [180]:
billboard=pd.read_csv("C:/Users\student/Downloads/Python_JP/data/billboard.csv")
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [183]:
pd.melt(billboard,id_vars=['year','artist','track','time','date.entered'],
       var_name='week',value_name='rating')

year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]

In [204]:
s=pd.Series(range(10))
s[3]=np.nan
s
s.count() #nan갯수 누락

df=pd.DataFrame(np.random.randint(5,size=(4,4)),dtype=float)
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic.head()
titanic.count()
#타이타닉은 데이타프레임이지만, 각 열별로 시리즈 카운트?

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [212]:
np.random.seed(777)
s2=pd.Series(np.random.randint(6,size=100))
s2
#s2.count()
s2.value_counts()
#종류별로 데이터 갯수를 count
# df.value_counts() # error 열별로 count 해줘야함...
df[0].value_counts()

3.0    2
1.0    1
2.0    1
Name: 0, dtype: int64

In [215]:
s2.value_counts().sort_index()#인덱스 기준 정렬

0    20
1    11
2    15
3    15
4    19
5    20
dtype: int64

In [226]:
s.sort_values()#값을 기준으로 정렬(nan 맨뒤)
s.sort_values(ascending=False)#오름차순 정렬
df.sort_values(by=3)#by열 기준으로 정렬
df.sort_values(by=[1,2])#1번열이 같으면 2번열 기준으로 정렬

0    1    2    3
0  2.0  0.0  0.0  4.0
3  3.0  1.0  0.0  3.0
1  3.0  1.0  1.0  1.0
2  1.0  1.0  4.0  4.0

In [238]:
df=pd.DataFrame(np.random.randint(10,size=(4,8)))
df["Mysum"]=df.sum(axis=1)
df

0  1  2  3  4  5  6  7  Mysum
0  8  1  4  3  6  8  5  9     44
1  0  6  1  8  2  7  1  3     28
2  9  7  5  3  1  4  5  5     39
3  5  5  5  1  9  6  3  6     40

In [239]:
df.sum(axis=0)

0         22
1         19
2         15
3         15
4         18
5         25
6         14
7         23
Mysum    151
dtype: int64

In [240]:
df.loc["total",:]=df.sum()
df

0     1     2     3     4     5     6     7  Mysum
0       8.0   1.0   4.0   3.0   6.0   8.0   5.0   9.0   44.0
1       0.0   6.0   1.0   8.0   2.0   7.0   1.0   3.0   28.0
2       9.0   7.0   5.0   3.0   1.0   4.0   5.0   5.0   39.0
3       5.0   5.0   5.0   1.0   9.0   6.0   3.0   6.0   40.0
total  22.0  19.0  15.0  15.0  18.0  25.0  14.0  23.0  151.0

In [243]:
#실수 데이터 -> 카테고리화
#cut(실수 값의 경계 지정),
#qcut(똑같은 구간으로 나눔)
ages=[0,2,10,21,23,37,31,61,20,42,32,100]
bins=[1,15,25,35,60,99]
labels=["미성년자","청년","중년","장년","노년"]
cats=pd.cut(ages,bins,labels=labels)
cats

[NaN, 미성년자, 미성년자, 청년, 청년, ..., 노년, 청년, 장년, 중년, NaN]
Length: 12
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [244]:
cats.categories
cats.codes

array([-1,  0,  0,  1,  1,  3,  2,  4,  1,  3,  2, -1], dtype=int8)

In [245]:
ages

[0, 2, 10, 21, 23, 37, 31, 61, 20, 42, 32, 100]

In [252]:
df=pd.DataFrame(ages,columns=["ages"])
df['age_cut']=pd.cut(ages,bins,labels=labels)
df

ages age_cut
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      장년
6     31      중년
7     61      노년
8     20      청년
9     42      장년
10    32      중년
11   100     NaN

In [258]:
data=np.random.randn(100)
data
cats=pd.qcut(data,4,labels=['Q1','Q2','Q3','Q4'])
cats
pd.value_counts(cats)

Q4    25
Q3    25
Q2    25
Q1    25
dtype: int64

In [7]:
#문제1 
# Pclass 원핫인코딩
# Age 이산화(5구간)
# Fare를 이산화(3구간)
# embarked를 원핫인코딩
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
pew=pd.read_csv("train.csv")
pew
# ohe=OneHotEncoder()
# ohe.transform(pew).toarray()
print(pd.get_dummies(pew['Pclass']))
pew.ix[:,['Age']]
AgeCut=pd.qcut(pew.Age,5,labels=['a',"b","c",'d','e'])
print(AgeCut)
FareCut=pd.qcut(pew.Fare,3,labels=['s','m','l'])
print(FareCut)
print(pd.get_dummies(pew['Embarked']))
# pew.Age

     1  2  3
0    0  0  1
1    1  0  0
2    0  0  1
3    1  0  0
4    0  0  1
..  .. .. ..
886  0  1  0
887  1  0  0
888  0  0  1
889  1  0  0
890  0  0  1

[891 rows x 3 columns]
0        b
1        d
2        c
3        d
4        d
      ... 
886      c
887      a
888    NaN
889      c
890      d
Name: Age, Length: 891, dtype: category
Categories (5, object): [a < b < c < d < e]
0      s
1      l
2      s
3      l
4      s
      ..
886    m
887    l
888    m
889    l
890    s
Name: Fare, Length: 891, dtype: category
Categories (3, object): [s < m < l]
     C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]


In [21]:
#문제2
word="apple is so pretty"
listd=[]
for i in word:
    listd.append(i)
for i in range(len(listd)-1,-1,-1):
    print(listd[i],end="")
print()
for i in range(0,len(listd)):
    print(listd.pop(),end="")

ytterp os si elppa
ytterp os si elppa

In [25]:
#문제3
ns=[1,3,5,1,3,5,1,3,5]
nss=list(set(ns))
newl=[]
print(nss)
for i in range(0,8):
    if i==0:
        newl.append(ns[i])
    elif ns[i]!=ns[i+1] and ns[i] not in newl:
        newl.append(ns[i])
print(newl)

[1, 3, 5]
[1, 3, 5]


In [ ]:
#문제4
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd
import numpy as np
bins=[1,15,25,35,60,99]
labels=["미성년자","청년","중년","장년","노년"]
