In [8]:
# numpy(전처리). pandas(분석)
# matplotlib, seaborn 시각화

'''
전처리 : 결측치, 표준화, 정규화

정규화 : (각 속성값-최소값) / (각 속성의 최대값 - 최소값) => 0~1사이의 값으로
표준화 : 평균을 0으로 표준편차를 1로 (각 속성값-평균) / 표준편차
one-hot encoding : 메모리 낭비 심함 => 사이즈가 작은 것은 괜찮지만 큰건 비효율 => 밀집벡터
밀집벡터(워드2벡터)
'''

'\n전처리 : 결측치, 표준화, 정규화\n\n정규화 : (각 속성값-최소값) / (각 속성의 최대값 - 최소값) => 0~1사이의 값으로\n표준화 : 평균을 0으로 표준편차를 1로 (각 속성값-평균) / 표준편차\none-hot encoding : 메모리 낭비 심함 => 사이즈가 작은 것은 괜찮지만 큰건 비효율 => 밀집벡터\n밀집벡터(워드2벡터)\n'

In [9]:
'''
리스트 : 속도 느림, 메모리 많이 차지
배열(array) : 속도 빠름, 메모리 적게 차지

넘파이 배열과 리스트의 차이점
- 리스트: 모든 데이터저장 가능
- 배열: 모두 같은 자료형으로 통일해 주어야함, 원소개수 변경 못함
- 배열은 파이썬에서 제공하지 않음
- 파이썬 환경에서 넘파이 패키지를 활용하여 배열을 사용할 수 있음


넘파이 : 수치해서 패키지, 다차원 배열 구조 
        벡터, 행렬을 사용하는 선행대수 계산시 사용
        넘파이 배열 연산 빠름(벡터화 연산)'''

'\n리스트 : 속도 느림, 메모리 많이 차지\n배열(array) : 속도 빠름, 메모리 적게 차지\n\n넘파이 배열과 리스트의 차이점\n- 리스트: 모든 데이터저장 가능\n- 배열: 모두 같은 자료형으로 통일해 주어야함, 원소개수 변경 못함\n- 배열은 파이썬에서 제공하지 않음\n- 파이썬 환경에서 넘파이 패키지를 활용하여 배열을 사용할 수 있음\n\n\n넘파이 : 수치해서 패키지, 다차원 배열 구조 \n        벡터, 행렬을 사용하는 선행대수 계산시 사용\n        넘파이 배열 연산 빠름(벡터화 연산)'

In [1]:
#1차원 배열
import numpy
ar=numpy.array([0,1,2,3,4])
ar
type(ar)

numpy.ndarray

In [2]:
#100*100 크기의 이미지 픽셀 :10000개
#    0~255사이의 gray scale
#    => 몇차원? 10000차원...???

In [14]:
data=list(range(0,10))
#data에 저장된 모든 값들에 대해 2배
# for i in range(0,10):
#     data[i]=data[i]*2
data=list(range(0,20,2))# 2띄엄띄엄
print(data)

# 시간복잡도(CPU)
# 연산 결과가 나오기까지 수해오디는 라인의 수
# 빅오 O(1) 은 1번수행되는 것만 의미가 아니라 횟수가 정해진 상수 복잡도
# 예로 어떠한 함수가 항상 5번 수행인 O(5)도 O(1)로 표기

# 공간 복잡도(MEM) <- 차지하게 되는 메모리 양
#

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [16]:
data1=list(range(0,10))
ans=[]
for i in data1:
    ans.append(i*2)
print(ans)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [17]:
import numpy as np
x=np.array(data)
x*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a2=[1,2,3]
b2=[4,5,6]

In [22]:
print(2*a2+b2)
print(2*a+b) #벡터화 연산
#리스트 연산은 덧셈이 append

[1, 2, 3, 1, 2, 3, 4, 5, 6]
[ 6  9 12]


In [24]:
#a
a2==2
a==2

array([False,  True, False])

In [ ]:
# 2차원 배열 (행렬, matrix)
# 가로줄 : 행, 세로줄 : 열

In [31]:
# 2차원 배열 : 리스트의 리스트
m=[[0,1,2],[3,4,5]]
# 열 : 안쪽 리스트 길이, 가로 크기
# 행 : 바깥쪽 리스트 길이, 세로 크기
# 2행 3열
# 0 1 2
# 3 4 5
len(m) #행의 개수
len(m[0]) #열의 개수

3

In [73]:
# 3차원 배열 : 리스트의 리스트의 리스트
m=np.array([[[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]],
        [[31,2,3,4],
        [35,6,7,8],
        [39,10,11,12]]])
# 2행 3열 4깊이(면)
# 2*3*4
len(m)
len(m[0])
len(m[0][0])
print(m.ndim)
print(m.shape)

3
(2, 3, 4)


In [38]:
a=np.array([4,5,6])
a.ndim#배열의 차원
a.shape #배열의 크기


(3,)

In [41]:
m=np.array([[0,1,2],[3,4,5]])
m.ndim
m.shape # 2행 3열


(2, 3)

In [147]:
#1.연속으로 숫자 3개를 곱했을때 얻어진 결과값이 가장 큰 구간이 어디인지
listdata=[]
data=[3,2,1,-4,-7,-9,8,-5,3,-1]
print("문제1")
for i in range(0,8):
    listdata.append(data[i]*data[i+1]*data[i+2])
print(listdata)
for i in range(0,8):
    if listdata[i]==max(listdata):
        print("max는 :",max(listdata))
        print("(",data[i],",",data[i+1],",",data[i+2],"), ",end="")
        print("data[",i,"~",i+2,"] 구간",sep="")

    

#2
#2*2의 영역을 구성하는 수를 곱했을때 얻어진 결과값이 가장 큰 구간어디
arrb = np.array([[3,1,-2],[2,-1,-3],[-2,0,-7]])
listb=[]
print("\n문제2")
for i in range(0,2):
    for j in range(0,2):
        listb.append(arrb[i][j]*arrb[i+1][j]*arrb[i][j+1]*arrb[i+1][j+1])
arrT=np.array([[0,0],[0,0]])
count=0
for i in range(0,2):
    for j in range(0,2):
        arrT[i][j]=listb[count]
        count+=1
print(arrT)
for i in range(0,2):
    for j in range(0,2):
        if arrT[i][j]==np.max(arrT):
            print("arrb[",i+1,"][",j+1,"],arrb[",i+1,"][",j+2,"],arrb[",i+2,"][",j+1,"],arrb[",i+2,"][",j+2,"]",sep="")
#print(listb)

문제1
[6, -8, 28, -252, 504, 360, -120, 15]
max는 : 504
( -7 , -9 , 8 ), data[4~6] 구간

문제2
[[-6 -6]
 [ 0  0]]
arrb[2][1],arrb[2][2],arrb[3][1],arrb[3][2]
arrb[2][2],arrb[2][3],arrb[3][2],arrb[3][3]


In [71]:
#array slicing
ar=np.array([[1,2,3,4],[5,6,7,8]])
ar
print(ar[0])
print(ar[0,:])#첫번째 행 전체
print(ar[:,1]) #전체 행에서 2번째열
print(ar[1,1:])#두번째 행에서 두번째 열부터 마지막까지
print(ar[:,:2])# 1,2,5,6 나오게
print(ar[0:2,0:2])

[1 2 3 4]
[1 2 3 4]
[2 6]
[6 7 8]
[[1 2]
 [5 6]]
[[1 2]
 [5 6]]


In [84]:
#indexing : 데이터 1개를 참조
ar=np.array([0,1,2])
ar[1]
ar[-1]
ar=np.array([[1,2,3,4],[5,6,7,8]])
print(ar[0,0])# 다차원 배열에서는컴마로 접근
print(ar[1,1])
print(ar[-1])
print(ar[-1,1])
print(ar[-1][1])
print(ar[-1,-3])


1
6
[5 6 7 8]
6
6
6


In [98]:
#불린 참조 : 조건에 대해 만족하는 값을 추출
ar=np.array([2,3,4,5])
bidx=np.array([True, True, False, True])
ar[bidx]
print(ar!=5)
# ar 요소값이 짝수인 것들만 추출
print(ar%2==0)
print(ar[ar%2==0])
# ar 요소값이 3보다 큰 값들만
print(ar[ar>3])

[ True  True  True False]
[ True False  True False]
[2 4]
[4 5]


In [100]:
#정수 참조 추출
ar=np.array([2,3,4,5])
idx=np.array([0,3])
ar[idx]
idx=np.array([0,0,1,1])
ar[idx]

array([2, 2, 3, 3])

In [112]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
#[[1,5],
#[5,8]]
idx=np.array([0,3])
print(ar[:,idx])
print(ar[:,(0,3)])
print(ar[:,[0,3]])
print(ar[:,[True,False,False,True]])

[[1 4]
 [5 8]]
[[1 4]
 [5 8]]
[[1 4]
 [5 8]]
[[1 4]
 [5 8]]


In [114]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
print(ar[:])#전체 행
print(ar)#배열 전체
print(ar[:,:])#전체 행 전체 열


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [118]:
ar=np.array([[1,2,3,4],
             [15,16,17,18],
             [25,26,27,28],
             [35,36,37,38]])
print(ar[2,:])
print(ar[[2,0],:])
print(ar[[2,0,-1],:])

[25 26 27 28]
[[25 26 27 28]
 [ 1  2  3  4]]
[[25 26 27 28]
 [ 1  2  3  4]
 [35 36 37 38]]


In [ ]:
# 원데이터 : csv(콤마로 구분형태), tsv(테이블로 구분형태), txt, xls, xlsx, json, ...
# Pandas : 데이터프레임-원데이터를 데이터프레임으로 읽어서 분석
# Numpy : 다차원배열-원데이터를 다차원배열로 읽어서 처리


In [122]:
import pandas as pd
csvTest=pd.read_csv("test_csv.csv")
print(csvTest)
print(type(csvTest))

   ID LAST_NAME  AGE
0   1       KIM   25
1   1       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30
<class 'pandas.core.frame.DataFrame'>


In [123]:
#http://pandas.pydata.org
csvTest.shape[1]

3

In [132]:
#test_txt.txt
#구분자:|
text=pd.read_csv("test_txt.txt")
print(text)
print(text.shape)
text=pd.read_csv("test_txt.txt",sep="|")
print(text)
print(text.shape)

  ID|LAST_NAME|AGE
0         1|KIM|25
1         1|LEE|22
2        3|PARK|33
3        4|CHOI|24
4        5|CHO|30B
(5, 1)
   ID LAST_NAME  AGE
0   1       KIM   25
1   1       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO  30B
(5, 3)


In [166]:
#문제3
m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
#print(m)
print(m[1,2])
print(m[-1,-1])
print(m[1,(1,2)])
print(m[(0,1),2])
print(m[(0,1),3:])
print(m[0:2,3:5])

7
14
[6 7]
[2 7]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


In [212]:
#문제4
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(x[x%3==0])
print(x[x%4==1])
x=np.array(x[x%4==1])
# t=[x%4==1]
# print(x[t][x[t]%3==0])
print(x[x%3==0])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [268]:
#문제5
boxData=[7,4,2,0,0,6,0,7,0]
boxData=np.array(boxData)
x=100
y=100
arr=[[0]*y]*x
arr=np.array(arr)
# print(arr)
for i in range(0,len(boxData)):
    for j in range(0,boxData[i]):
        arr[i][j]=1
arr2=[[0]*x]*y
arr2=np.array(arr2)
for i in range(0,x):
    for j in range(0,y):
        arr2[i][j]=arr[j][i]
print(arr)
print(arr2)#회전 데이터
listResult=[]# 0갯수 카운트를 위한 리스트
for i in range(0,x):
    count=0
    for j in range(0,y):
        if arr2[i][j]==1:
            for k in range(j+1,y):
                if arr2[i][k]==0:
                    count+=1
#                     print(i,j,count)
            break;        
    listResult.append(count)    
print(listResult)
print(max(listResult))
    
            

[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[95, 95, 96, 96, 97, 97, 98, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
98
