In [44]:
import pandas as pd
import numpy as np
#from pandas import *
from pandas import DataFrame

In [46]:
#pd.DataFrame()
#DataFrame()
#pandas.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [12]:
print(pd.read_csv("test_txt.txt", sep="|"))
# 디폴트 행 인덱스 : 0번 ~ 
print(pd.read_csv("test_txt.txt", sep="|", index_col='ID'))
print(pd.read_csv("test_txt.txt", sep="|", index_col=0))
print(pd.read_csv("test_txt.txt", sep="|", index_col=1))
print(pd.read_csv("test_txt.txt", sep="|", index_col=2))

   ID LAST_NAME  AGE
0   1       KIM   25
1   1       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO  30B
   LAST_NAME  AGE
ID               
1        KIM   25
1        LEE   22
3       PARK   33
4       CHOI   24
5        CHO  30B
   LAST_NAME  AGE
ID               
1        KIM   25
1        LEE   22
3       PARK   33
4       CHOI   24
5        CHO  30B
           ID  AGE
LAST_NAME         
KIM         1   25
LEE         1   22
PARK        3   33
CHOI        4   24
CHO         5  30B
     ID LAST_NAME
AGE              
25    1       KIM
22    1       LEE
33    3      PARK
24    4      CHOI
30B   5       CHO


In [16]:
print(pd.read_csv("test_text_without_name.txt", sep="|",index_col=0))
#header = 있음, 디폴트 설정되어 있음
print(pd.read_csv("test_text_without_name.txt", header=None, sep="|",index_col=0))

    KIM   25
1           
1   LEE   22
3  PARK   33
4  CHOI   24
5   CHO  30B
      1    2
0           
1   KIM   25
1   LEE   22
3  PARK   33
4  CHOI   24
5   CHO  30B


In [23]:
print(pd.read_csv("test_txt.txt", sep="|",skiprows=1))
#헤더의 역할
print(pd.read_csv("test_txt.txt", sep="|",skiprows=2))
#연속적으로 여러 줄을 건너뛸 경우
print(pd.read_csv("test_txt.txt", sep="|",skiprows=[1,3]))
#비연속적으로 여러 줄을 건너뛸경우
pd.read_csv("test_txt.txt", sep="|",skiprows=[0,2])
data=pd.read_csv("test_txt.txt", sep="|",nrows=3)
data.info()

   1   KIM   25
0  1   LEE   22
1  3  PARK   33
2  4  CHOI   24
3  5   CHO  30B
   1   LEE   22
0  3  PARK   33
1  4  CHOI   24
2  5   CHO  30B
   ID LAST_NAME  AGE
0   1       LEE   22
1   4      CHOI   24
2   5       CHO  30B
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
ID           3 non-null int64
LAST_NAME    3 non-null object
AGE          3 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [ ]:
#결측값

In [31]:
data=pd.read_csv("test_text_na.txt", sep="|")
data

ID LAST_NAME AGE
0   1       KIM  25
1   1       LEE  없음
2   3      PARK  33
3   4        모름  24
4   5       CHO  30

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes


In [34]:
data=pd.read_csv("test_text_na.txt", sep="|",na_values=['없음',"모름"])
#na_values - not available values
#nan = not a number
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int64
LAST_NAME    4 non-null object
AGE          4 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes


ID LAST_NAME   AGE
0   1       KIM  25.0
1   1       LEE   NaN
2   3      PARK  33.0
3   4       NaN  24.0
4   5       CHO  30.0

In [36]:
#데이터 타입 지정
data=pd.read_csv("test_text_na.txt", sep="|",
                dtype={'ID':int,'LAST_NAME':str,'AGE':str})
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
ID           5 non-null int32
LAST_NAME    5 non-null object
AGE          5 non-null object
dtypes: int32(1), object(2)
memory usage: 228.0+ bytes


ID LAST_NAME AGE
0   1       KIM  25
1   1       LEE  없음
2   3      PARK  33
3   4        모름  24
4   5       CHO  30

In [48]:
from pandas import DataFrame
#딕셔너리 데이터로 데이터프레임 생성하기
df=DataFrame({
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]
})
df
# DataFrame.to_csv함수 : 데이터프레임을 csv로 저장


id  x1   x2
0  a1   1  1.1
1  a2   2  2.2
2  a3   3  3.3
3  a4   4  4.4
4  a5   5  5.5

In [50]:
from pandas import DataFrame
#딕셔너리 데이터로 데이터프레임 생성하기
df=DataFrame(data={
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]
},index=['a','b','c','d','e'])
# 인덱스 옵션을 넣어 행 인덱스 원하는대로 바꾸기
# 데이터프레임의 인수 갯수 2개. 딕셔너리랑, index
df

id  x1   x2
a  a1   1  1.1
b  a2   2  2.2
c  a3   3  3.3
d  a4   4  4.4
e  a5   5  5.5

In [55]:
from pandas import DataFrame
#딕셔너리 데이터로 데이터프레임 생성하기
df=DataFrame(data={
    'id':['a1','a2','a3','a4','a5'],
    'x1':[1,2,3,4,5],
    'x2':[1.1,2.2,3.3,4.4,5.5]
},index=['a','b','c','d','e'])
df
#결측값으로 구성된 새로우 행 추가
df2=df.reindex(['a','b','c','d','e','f'])
df2
df3=df.reindex(['a','c','e','f'])
df3
df4=df.reindex(['a','k','c','e','f'])
df4

id   x1   x2
a   a1  1.0  1.1
k  NaN  NaN  NaN
c   a3  3.0  3.3
e   a5  5.0  5.5
f  NaN  NaN  NaN

In [61]:
df2.to_csv("df2.csv")

In [58]:
df2.to_csv("df3.csv",sep="$")

In [62]:
df2.to_csv("df4.csv", na_rep="누락", header=None)
# 값 없는거 누락으로 출력, 헤더 없이 저장

In [63]:
df2.to_csv("df4.csv", na_rep="누락", float_format="%.2f")
#출력 소숫점 둘째자리까지

In [66]:
df2.to_csv("df5.csv", na_rep="NaN", columns=['id','x2'])
#원하는 컬럼만 저장

In [67]:
df2.to_csv("df6.csv", na_rep="NaN", columns=['id','x2'],index=False)
#행 인덱스 빠짐

In [69]:
from pandas import DataFrame as df

In [73]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
df(data=np.arange(8).reshape(4,2))
# 1차원 배열 2차원 배열로 재정의
# 데이터프레임에 딕셔너리 뿐만 아니라 다른 자료형(array)가능

0  1
0  0  1
1  2  3
2  4  5
3  6  7

In [74]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [79]:
df(data=np.arange(8).reshape(4,2),columns=['col0','col1'],
   index=['row0','row1','row2','row3'])
#컬럼의 이름을 변경, #로우의 이름을 변경

col0  col1
row0     0     1
row1     2     3
row2     4     5
row3     6     7

In [80]:
df1=df(data=np.arange(8).reshape(4,2),columns=['col0','col1'],
   index=['row0','row1','row2','row3'])
type(df1)

pandas.core.frame.DataFrame

In [81]:
df1
#transpose matrix

col0  col1
row0     0     1
row1     2     3
row2     4     5
row3     6     7

In [82]:
df1.T

row0  row1  row2  row3
col0     0     2     4     6
col1     1     3     5     7

In [83]:
df1.axes
#axis(축,단수), axes(복수)

[Index(['row0', 'row1', 'row2', 'row3'], dtype='object'),
 Index(['col0', 'col1'], dtype='object')]

In [84]:
df1.dtypes

col0    int32
col1    int32
dtype: object

In [85]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row0 to row3
Data columns (total 2 columns):
col0    4 non-null int32
col1    4 non-null int32
dtypes: int32(2)
memory usage: 224.0+ bytes


In [91]:
print(df1.shape)
print(df1.shape[0])
print(df1.shape[1])

(4, 2)
4
2


In [92]:
df1.size

8

In [93]:
df1.values

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [98]:
np.random.randn(5) #평균:0, 표준편차:1 인 분포로부터 난수 발생

array([0.27728948, 0.31541613, 1.05701884, 0.53156097, 0.1226905 ])

In [101]:
df=DataFrame({"cls_1":['a','a','b','b','c'],
         "v1":np.arange(5),"v2":np.random.randn(5)},
         index=['r0','r1','r2','r3','r4']
         )

In [102]:
df.index

Index(['r0', 'r1', 'r2', 'r3', 'r4'], dtype='object')

In [103]:
df.ix

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [104]:
df

cls_1  v1        v2
r0     a   0 -0.213140
r1     a   1  0.926846
r2     b   2 -0.856499
r3     b   3 -1.037536
r4     c   4  0.426738

In [113]:
import warnings #워닝 메시지 무시
warnings.filterwarnings(action='ignore')
df.ix[2] #행 위치(0번부터 시작)
df.ix['r2'] #행 인덱스 이름
#ix는 행 단위 indexing할때, 행 위치(정수)와 행 인덱스 이름을
#모두 사용할 수 있다.
df.ix[3:]
df.ix['r3':]

cls_1  v1        v2
r3     b   3 -1.037536
r4     c   4  0.426738

In [118]:
df
df.head(3)
df.tail(3)

cls_1  v1        v2
r2     b   2 -0.856499
r3     b   3 -1.037536
r4     c   4  0.426738

In [119]:
df['r1':]

cls_1  v1        v2
r1     a   1  0.926846
r2     b   2 -0.856499
r3     b   3 -1.037536
r4     c   4  0.426738

In [120]:
df['cls_1']
df.cls_1
type(df[[cls=1])

r0    a
r1    a
r2    b
r3    b
r4    c
Name: cls_1, dtype: object

In [156]:
#df1[['cls_1']]

In [126]:
df.reindex(['r0','r1','r2','r5','r6'])

cls_1   v1        v2
r0     a  0.0 -0.213140
r1     a  1.0  0.926846
r2     b  2.0 -0.856499
r5   NaN  NaN       NaN
r6   NaN  NaN       NaN

In [129]:
df.reindex(['r0','r1','r2','r5','r6'],fill_value=0)
df.reindex(['r0','r1','r2','r5','r6'],fill_value='missing')
#df.reindex(['r0','r1','r2','r5','r6'],fill_value='NA')

cls_1       v1        v2
r0        a        0  -0.21314
r1        a        1  0.926846
r2        b        2 -0.856499
r5  missing  missing   missing
r6  missing  missing   missing

In [139]:
#시계열 데이터 : DataFrame에서 index를 만들때 data_range함수
date_idx=pd.date_range("1/7/2020",periods=5, freq="d")

In [135]:
df2=pd.DataFrame({"c1":[5,3,7,6,4]})
df2

c1
0   5
1   3
2   7
3   6
4   4

In [140]:
df2=pd.DataFrame({"c1":[5,3,7,6,4]},index=date_idx)
df2

c1
2020-01-07   5
2020-01-08   3
2020-01-09   7
2020-01-10   6
2020-01-11   4

In [144]:
date_idx2=pd.date_range("1/1/2020",periods=20, freq="D")
date_idx2

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20'],
              dtype='datetime64[ns]', freq='D')

In [152]:
# df3=pd.DataFrame({"c1":[5,3,7,6,4]},index=date_idx2)
# df3
df2.reindex(date_idx2,fill_value=0)

c1
2020-01-01   0
2020-01-02   0
2020-01-03   0
2020-01-04   0
2020-01-05   0
2020-01-06   0
2020-01-07   5
2020-01-08   3
2020-01-09   7
2020-01-10   6
2020-01-11   4
2020-01-12   0
2020-01-13   0
2020-01-14   0
2020-01-15   0
2020-01-16   0
2020-01-17   0
2020-01-18   0
2020-01-19   0
2020-01-20   0

In [154]:
# df3=pd.DataFrame({"c1":[5,3,7,6,4]},index=date_idx2)
# df3
df2.reindex(date_idx2,method="ffill")
df2.reindex(date_idx2,method="bfill")

c1
2020-01-01  5.0
2020-01-02  5.0
2020-01-03  5.0
2020-01-04  5.0
2020-01-05  5.0
2020-01-06  5.0
2020-01-07  5.0
2020-01-08  3.0
2020-01-09  7.0
2020-01-10  6.0
2020-01-11  4.0
2020-01-12  NaN
2020-01-13  NaN
2020-01-14  NaN
2020-01-15  NaN
2020-01-16  NaN
2020-01-17  NaN
2020-01-18  NaN
2020-01-19  NaN
2020-01-20  NaN

In [ ]:
#uci.edu data <- 캘리포니아 대학 오픈 데이터 자료

In [161]:
#문제1
import pandas as pd
import numpy as np
from pandas import DataFrame as df
data=pd.read_csv("zoo.data")
data


aardvark  1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  \
0   antelope  1  0    0    1    0    0    0    1    1    1    0    0  4    1   
1       bass  0  0    1    0    0    1    1    1    1    0    0    1  0    1   
2       bear  1  0    0    1    0    0    1    1    1    1    0    0  4    0   
3       boar  1  0    0    1    0    0    1    1    1    1    0    0  4    1   
4    buffalo  1  0    0    1    0    0    0    1    1    1    0    0  4    1   
..       ... .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...   
95   wallaby  1  0    0    1    0    0    0    1    1    1    0    0  2    1   
96      wasp  1  0    1    0    1    0    0    0    0    1    1    0  6    0   
97      wolf  1  0    0    1    0    0    1    1    1    1    0    0  4    1   
98      worm  0  0    1    0    0    0    0    0    0    1    0    0  0    0   
99      wren  0  1    1    0    1    0    0    0    1    1    0    0  2    1   

    0.7  1.6  1.7  
0     0    1    1  
1     0    0    4  
2     0    1    1  
3     0    1    1  
4     0    1    1  
..  ...  ...  ...  
95    0    1    1  
96    0    0    6  
97    0    1    1  
98    0    0    7  
99    0    0    2  

[100 rows x 18 columns]

In [223]:
#문제2
boxData=[5,8,3,1,5,6,9,9,2,2,4]
boxData=np.array(boxData)
for i in range(0,11):
    print(boxData,max(boxData)-min(boxData))
    print()
    for j in range(0,11):
        if boxData[j]==max(boxData):
            boxData[j] = boxData[j]-1
            for k in range(0,11):     
                if boxData[k]==min(boxData):
                    boxData[k]+=1
                    break
            break
    

[5 8 3 1 5 6 9 9 2 2 4] 8

[5 8 3 2 5 6 8 9 2 2 4] 7

[5 8 3 3 5 6 8 8 2 2 4] 6

[5 7 3 3 5 6 8 8 3 2 4] 6

[5 7 3 3 5 6 7 8 3 3 4] 5

[5 7 4 3 5 6 7 7 3 3 4] 4

[5 6 4 4 5 6 7 7 3 3 4] 4

[5 6 4 4 5 6 6 7 4 3 4] 4

[5 6 4 4 5 6 6 6 4 4 4] 2

[5 5 5 4 5 6 6 6 4 4 4] 2

[5 5 5 5 5 5 6 6 4 4 4] 2



In [239]:
#문제2
boxData1=[5,8,3,1,5,6,9,9,2,2,4]
boxData1=np.array(boxData1)
boxData2=boxData1
boxData2=np.array(boxData2)
listMax=[]
listMin=[]
for i in range(0,10):
    for j in range(0,11):
        if boxData1[j]==max(boxData1):
            listMax.append(boxData1[j])
            boxData1[j]=boxData1[j]-1
for i in range(0,10):
    for j in range(0,11):
        if boxData2[j]==min(boxData2):
            listMin.append(boxData2[j])
            boxData2[j]=boxData2[j]+1
for i in range(0,11):
    print(listMax[i]-listMin[i],end=' ')


8 7 6 6 5 4 4 4 2 2 2 