In [1]:
import nltk
nltk.__version__

'3.4.5'

In [2]:
nltk.download()
#nltk.download('treebank') #treebank 별도 설치
#github.com/nltk

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
#pip install konlpy
import konlpy

In [4]:
konlpy.__version__

'0.5.2'

In [5]:
#JPype : 자바와 파이썬 연결

In [6]:
#토큰화, 정제, 정규화
#토큰(단어)화:어절, 단어, 문장, 문단
#단어토큰화 : 구두점, 특수문자 제거
from nltk.tokenize import word_tokenize

In [9]:
print(word_tokenize("Mr. Jone's Don't be "))

['Mr.', 'Jone', "'s", 'Do', "n't", 'be']


In [29]:
from nltk.tokenize import WordPunctTokenizer
print(WordPunctTokenizer().tokenize("Mr. Jone's Don't be "))

['Mr', '.', 'Jone', "'", 's', 'Don', "'", 't', 'be']


In [12]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [13]:
print(text_to_word_sequence("Mr. Jone's Don't be "))

['mr', "jone's", "don't", 'be']


In [15]:
#중요한건 정규표현식

In [19]:
from nltk.tokenize import TreebankWordTokenizer

In [22]:
twt=TreebankWordTokenizer()
print(twt.tokenize("Mr. Jone's Don't be "))

['Mr.', 'Jone', "'s", 'Do', "n't", 'be']


In [26]:
from nltk.tokenize import sent_tokenize
text="Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

In [27]:
print(sent_tokenize(text))
#len(sent_tokenize(text)) #3

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [30]:
print(sent_tokenize(text))
# 조사:she her 그녀가(에게, 를, 와, 는....)
# 아버지가방에 들어가...
# 한국어(형태소) 토큰화 작업 : 
# 형태소(가장 작은 말의 단위) 고려
# 자립형태소(길동이)/의존형태소
# ex)길동이가 파이썬을 합니다.

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [33]:
#토큰화 과정에서 단어가 어떤 품사로 쓰였는지
#품사 태깅(tagging), fly
text="Python is an interpreted, high-level, general-purpose programming language."
print(word_tokenize(text))
from nltk.tag import pos_tag
pos_tag(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [34]:
# 형태소 분석기: Okt, Mecab, Kkma,...
# Okt가 괜찮은듯하다고 함
# 단어 토큰화가 아님. 형태소 토큰화를 하는 것임
from konlpy.tag import Okt

In [36]:
okt=Okt()
#Okt와 JPye1 버전 
#pip install jpype1==0.7.0

#morphs : 형태소 추출
print(okt.morphs("오늘은 수요일, 내일은 목요일입니다"))
#pos : 품사
print(okt.pos("오늘은 수요일, 내일은 목요일입니다"))
#nouns : 명사
print(okt.nouns("오늘은 수요일, 내일은 목요일입니다"))
#konlpy.org 사이트 참고

['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다']
[('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective')]
['오늘', '수요일', '내일', '목요일']


In [37]:
#데이터 정제(전처리):불필요한 형태소 제거, 단어
#정규표현식을 이용. 

In [38]:
#LSA

In [79]:
import numpy as np
#A 행렬은 DTM
A=np.array([[0,0,0,1,0,1,1,0,0],
            [0,0,0,1,1,0,1,0,0],
            [0,1,1,0,2,0,0,0,0],
            [1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

In [80]:
U,s, VT=np.linalg.svd(A,full_matrices=True)#full SVD, truncated SVD

In [81]:
U

array([[-2.39751712e-01,  7.51083898e-01,  5.48519247e-17,
        -6.15135834e-01],
       [-5.06077194e-01,  4.44029376e-01, -8.22778870e-17,
         7.39407727e-01],
       [-8.28495619e-01, -4.88580485e-01, -7.47642703e-17,
        -2.73649629e-01],
       [-9.04299898e-17, -4.11929620e-17,  1.00000000e+00,
         7.41190750e-17]])

In [82]:
U.round(2)#직교행렬 4*4

array([[-0.24,  0.75,  0.  , -0.62],
       [-0.51,  0.44, -0.  ,  0.74],
       [-0.83, -0.49, -0.  , -0.27],
       [-0.  , -0.  ,  1.  ,  0.  ]])

In [83]:
print(s.round(2))#4

[2.69 2.05 1.73 0.77]


In [84]:
S=np.zeros((4,9))
S[:4,:4]=np.diag(s)
print(S.round(2))

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


In [85]:
np.ones((4,9))*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [86]:
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


In [87]:
np.dot(np.dot(U,S),VT).round(2)#기존 A와 같음

array([[ 0.,  0.,  0.,  1., -0.,  1.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1.,  1., -0.,  1., -0., -0.],
       [ 0.,  1.,  1., -0.,  2., -0., -0.,  0.,  0.],
       [ 1., -0.,  0.,  0., -0.,  0., -0.,  1.,  1.]])

In [88]:
np.allclose(A,np.dot(np.dot(U,S),VT).round(2))

True

In [89]:
## 절단된(truncated) SVD
## 토픽 2개
## 대각선 위에 순서대로 가장 강한 토픽 의미
S=S[:2,:2]
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [91]:
U.shape #4,4
U=U[:,:2] #4,2 문서4개, 토픽2
#U의 의미는 4개 문서 각각에 대한 잠재된 의미를 표현
#하고 있는 수치 문서 벡터
U.round(2)

array([[-0.24,  0.75],
       [-0.51,  0.44],
       [-0.83, -0.49],
       [-0.  , -0.  ]])

In [93]:
VT.shape #(9,9)
VT=VT[:2,:]#(2,9) 토픽*단어개수
#VT의 각 열은 잠재 의미를 나타내기 위한 수치화된 
#단어 벡터

VT.round(2)
#U*S*VT != A

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ]])

In [94]:
Aprime=np.dot(np.dot(U,S),VT)
print(Aprime.round(2))
print(A)

[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]
[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


In [97]:
np.dot(S,VT).round(2)

array([[-0.  , -0.83, -0.83, -0.75, -2.16, -0.24, -0.75, -0.  , -0.  ],
       [ 0.  , -0.49, -0.49,  1.2 , -0.53,  0.75,  1.2 , -0.  , -0.  ]])

In [98]:
## 캐글 데이터 영화 유사도 

In [99]:
"""
          돈    사랑    저는    좋아요
줄거리1    0      1      1        1
줄거리2    1      0      1        1
줄거리3    2      0      2        2
"""
#norm 벡터의 크기 구하는 함수
from numpy.linalg import norm

In [100]:
mov1=np.array([0,1,1,1])
mov2=np.array([1,0,1,1])
mov3=np.array([2,0,2,2])

In [103]:
np.dot(mov1,mov2)#두 벡터의 내적
np.dot(mov1,mov2)/(norm(mov1)*norm(mov2))#코사인 유사도

def cos_sim(X,Y):
    return np.dot(X,Y)/(norm(X)*norm(Y))

In [104]:
print(cos_sim(mov1,mov2))
print(cos_sim(mov2,mov3))
print(cos_sim(mov1,mov3))

0.6666666666666667
1.0000000000000002
0.6666666666666667


In [130]:
import pandas as pd
data=pd.read_csv("C:/Users/student/Downloads/Python_JP/the-movies-dataset/movies_metadata.csv")
data=data.head(20000)
data.shape

C:\Users\student\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(20000, 24)

In [131]:
data['overview'].isnull().sum() #954
data['overview']=data['overview'].fillna('')

In [132]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english')
tfidf_mat=tfidf.fit_transform(data['overview'])
tfidf_mat.shape

(20000, 47487)

In [125]:
data['title']
#Toy Story와 가장 코사인 유사도가 큰
#영화 10편을 추출 -> 영화의 제목과 유사도 추출

0                                                Toy Story
1                                                  Jumanji
2                                         Grumpier Old Men
3                                        Waiting to Exhale
4                              Father of the Bride Part II
                               ...                        
19995                                            Rebellion
19996                                           Versailles
19997                                      Two in the Wave
19998    Lotte Reiniger: Homage to the Inventor of the ...
19999    RKO Production 601: The Making of 'Kong, the E...
Name: title, Length: 20000, dtype: object

In [126]:
data['overview'].head()

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [134]:
print(tfidf_mat)

  (0, 11645)	0.13942792746208266
  (0, 2811)	0.1524688231743182
  (0, 24325)	0.10272285889754121
  (0, 14393)	0.10323587624822204
  (0, 12920)	0.13359137839416452
  (0, 30780)	0.10362949000778948
  (0, 37778)	0.13329592929044795
  (0, 7974)	0.13030575543855816
  (0, 32424)	0.13359137839416452
  (0, 19047)	0.10485920860731182
  (0, 32291)	0.09637786759647918
  (0, 25229)	0.12052668500637997
  (0, 1254)	0.1489611323980068
  (0, 37166)	0.11699407550916606
  (0, 24759)	0.19553422928903877
  (0, 6290)	0.5036643709879097
  (0, 5775)	0.10961099833635705
  (0, 4736)	0.12600776612424489
  (0, 36185)	0.11514050233158798
  (0, 18727)	0.13359137839416452
  (0, 24957)	0.09146351035625488
  (0, 43131)	0.15491381382108724
  (0, 2051)	0.4159373110833513
  (0, 46617)	0.46474144146326174
  (0, 24361)	0.10943293956646011
  :	:
  (19997, 13221)	0.17897321248705433
  (19997, 37592)	0.15166031585027698
  (19997, 45919)	0.1821847673691749
  (19997, 46772)	0.14244710628029003
  (19997, 21552)	0.15423289582259