In [52]:
import tensorflow as tf
import numpy as np

In [66]:
tf.reset_default_graph()

In [67]:
idx2char=['h','i','e','l','o']
#hihello 문자열, hihell -> ihello
xdata=[[0,1,0,2,3,3]] #hihell (입력)
# [None,sequence_length,input_dim]
xOneHot=[[
    [1,0,0,0,0], #h
    [0,1,0,0,0], #i
    [1,0,0,0,0], #h
    [0,0,1,0,0], #e
    [0,0,0,1,0], #l
    [0,0,0,1,0]  #l
]]
ydata=[[1,0,2,3,3,4]]    #ihello (출력)

In [68]:
np.shape(xOneHot)

(1, 6, 5)

In [69]:
num_classes=5
input_dim=5     #원핫 크기
hidden_size=5   #RNN(LSTM) CELL에서 출력 크기
batch_size=1 #문장 1개
sequence_length=6
learning_rate=0.1

In [70]:
x=tf.placeholder(tf.float32,
                [None,sequence_length,input_dim])
y=tf.placeholder(tf.int32,[None,sequence_length])

In [71]:
cell=tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
initial_state=cell.zero_state(batch_size, tf.float32)
outputs, _states=tf.nn.dynamic_rnn(
cell, x,initial_state=initial_state, dtype=tf.float32
)

In [72]:
xForFc=tf.reshape(outputs,[-1, hidden_size])
outputs=tf.contrib.layers.fully_connected(
    inputs=xForFc, num_outputs=num_classes, 
    activation_fn=None
)
outputs=tf.reshape(outputs, 
                   [batch_size, 
                    sequence_length, 
                    num_classes])

In [73]:
weights=tf.ones([batch_size, sequence_length])

In [74]:
sequence_loss=tf.contrib.seq2seq.sequence_loss(logits=outputs, targets=y, weights=weights)

In [75]:
loss=tf.reduce_mean(sequence_loss)
train=tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [76]:
prediction=tf.argmax(outputs, axis=2)

In [77]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(100):
        lossv, _=sess.run([loss,train], feed_dict={x:xOneHot, y:ydata})
        res=sess.run(prediction,feed_dict={x:xOneHot})
        print(i, "cost:",lossv,"prediction:",res, "true Y :",ydata)
        
        s=[idx2char[c] for c in np.squeeze(res)]
        print("\nprediction str:","".join(s))
        

0 cost: 1.5927576 prediction: [[0 0 0 0 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhhhoo
1 cost: 1.5577682 prediction: [[0 0 0 4 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhhooo
2 cost: 1.5068083 prediction: [[0 0 0 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhheoo
3 cost: 1.4279814 prediction: [[2 0 2 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: eheeoo
4 cost: 1.3525299 prediction: [[2 0 2 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: eheeoo
5 cost: 1.283345 prediction: [[2 0 2 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: eheeoo
6 cost: 1.223448 prediction: [[2 0 2 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: eheeoo
7 cost: 1.1704919 prediction: [[2 0 2 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: eheeoo
8 cost: 1.1176835 prediction: [[2 0 2 2 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: eheeoo
9 cost: 1.0797019 prediction: [[2 0 2 0 4 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: ehehoo
10

86 cost: 0.80532223 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
87 cost: 0.80531293 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
88 cost: 0.8053039 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
89 cost: 0.80529517 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
90 cost: 0.8052867 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
91 cost: 0.8052786 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
92 cost: 0.80527085 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
93 cost: 0.8052631 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
94 cost: 0.8052557 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

prediction str: hhehho
95 cost: 0.8052485 prediction: [[0 0 2 0 0 4]] true Y : [[1, 0, 2, 3, 3, 4]]

predictio

In [23]:
x=np.array([1,2])
x.shape
y=np.expand_dims(x,axis=0)
y.shape

(1, 2)

In [24]:
y

array([[1, 2]])

In [26]:
[1, 2]  => axis 0 => [[1,2]]
[1, 2]  => axis 1 => [[1],[2]]

x=np.array([1,2])
x.shape
y=np.expand_dims(x,axis=1)
y.shape

(2, 1)

In [27]:
y

array([[1],
       [2]])

In [30]:
x=np.array([[[0],[1],[2]]])
x.shape
x

array([[[0],
        [1],
        [2]]])

In [29]:
np.squeeze(x)

array([0, 1, 2])

In [91]:
tf.reset_default_graph()

In [92]:
hidden_size=2
cell=tf.contrib.rnn.BasicLSTMCell
(num_units=hidden_size)
#출력 shape=(1,1,2)

In [93]:
xdata=np.array([[[1,0,0,0]]],
               dtype=np.float32)
#xdata shape=(1,1,4)

In [96]:
sess=tf.Session()
outputs,_states=tf.nn.dynamic_rnn
(cell,xdata,dtype=tf.float32)
sess.run(tf.global_variables_initializer())
print(sess.run(outputs))

[[[-0.05735544  0.05741299]]]


In [97]:
tf.reset_default_graph()

In [ ]:
#h -> [1, 0, 0, 0]
xdata=np.array([[h, e, l, l, o],
                [e, o, l, l, l],
                [l, l, e, e, l]],
               dtype=np.float32)
hidden_size=2
cell=tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)
sess=tf.Session()
outputs,_states=tf.nn.dynamic_rnn
(cell,xdata,dtype=tf.float32)
sess.run(tf.global_variables_initializer())
print(sess.run(outputs))

In [98]:
from tensorflow.examples.tutorials.mnist import input_data

In [99]:
mnist=input_data.read_data_sets
("./mnist/data/", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./mnist/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/datas

In [100]:
lr=0.01
total_epoch=30
batch_size=128

n_input=28 #한번에 입력받는 데이터 개수
n_step=28 #28줄
n_hidden=128 #셀에서 나가는 출력의 개수
n_class=10 #숫자의 종류(0~9)

In [106]:
w=tf.Variable(tf.random_normal([n_hidden, n_class]))
b=tf.Variable(tf.random_normal([n_class]))

In [101]:
x=tf.placeholder(tf.float32, [None, n_step, n_input])
y=tf.placeholder(tf.float32, [None, n_class])

In [102]:
#rnn 학습할 셀을 생성
cell=tf.nn.rnn_cell.BasicLSTMCell(num_units=n_hidden)

In [104]:
#rnn 망 구성
outputs,states=tf.nn.dynamic_rnn(cell,x,dtype=tf.float32)
#outputs : [batch_size,n_step,n_hidden]
# => 구조 변경(y형태로) => y:[batch_size,n_class]

#    0       ,   1 ,    2
#[batch_size,n_step,n_hidden]-> 
#[n_step, batch_size, n_hidden]
#    1,         0,        2
outputs=tf.transpose(outputs, [1,0,2])
outputs=outputs[-1]

In [107]:
model=tf.matmul(outputs,w)+b
cost=tf.reduce_mean(
    tf.nn.softmax_cross_entropy_
    with_logits_v2(logits=model, labels=y))
opt=tf.train.AdamOptimizer(lr).minimize(cost)

In [108]:
#신경망 모델 학습
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [109]:
total_batch=int(mnist.train.num_examples/batch_size)

In [110]:
for epoch in range(total_epoch):
    total_cost=0
    for i in range(total_batch):
        batchX,batchY=mnist.train.next_batch(batch_size)
        batchX=batchX.reshape((batch_size,n_step,n_input))
        #128,784 -> 128,28,28
        _,costv=sess.run([opt,cost],feed_dict={x:batchX,y:batchY})
        total_cost+=costv
    print("에폭:", "%4d" % (epoch+1),
         "cost 평균:", "{:.3f}".
          format(total_cost/total_batch))


에폭:    1 cost 평균: 0.364
에폭:    2 cost 평균: 0.092
에폭:    3 cost 평균: 0.065
에폭:    4 cost 평균: 0.054
에폭:    5 cost 평균: 0.044
에폭:    6 cost 평균: 0.040
에폭:    7 cost 평균: 0.042
에폭:    8 cost 평균: 0.036
에폭:    9 cost 평균: 0.034
에폭:   10 cost 평균: 0.031
에폭:   11 cost 평균: 0.034
에폭:   12 cost 평균: 0.032
에폭:   13 cost 평균: 0.025
에폭:   14 cost 평균: 0.028
에폭:   15 cost 평균: 0.026
에폭:   16 cost 평균: 0.028
에폭:   17 cost 평균: 0.026
에폭:   18 cost 평균: 0.026
에폭:   19 cost 평균: 0.026
에폭:   20 cost 평균: 0.030
에폭:   21 cost 평균: 0.028
에폭:   22 cost 평균: 0.023
에폭:   23 cost 평균: 0.018
에폭:   24 cost 평균: 0.022
에폭:   25 cost 평균: 0.021
에폭:   26 cost 평균: 0.026
에폭:   27 cost 평균: 0.022
에폭:   28 cost 평균: 0.024
에폭:   29 cost 평균: 0.024
에폭:   30 cost 평균: 0.025


In [112]:
isCorrect=tf.equal(tf.argmax(model,1), tf.argmax(y,1))
accuracy=tf.reduce_mean(tf.cast(isCorrect,tf.float32))
testSize=len(mnist.test.images)
testX=mnist.test.images.reshape(testSize, n_step, n_input)
testY=mnist.test.labels

print(sess.run(accuracy,feed_dict={x:testX, y:testY}))

0.9837
