In [1]:
import tensorflow as tf

In [2]:
a=tf.placeholder("float")
b=tf.placeholder("float")
#플레이스홀더:프로그램 실행 중에 값을 변경할
#수 있는 변수를 2개 정의
#데이터를 담는 버퍼와 같은 것


In [3]:
y=tf.multiply(a,b)
sess=tf.Session() 
#그래프 실행을 위해서는 세션이 필요
print(sess.run(y,feed_dict={a:3,b:2}))
#y노드를 실행해라

6.0


In [4]:
tensorflow.org


NameError: name 'tensorflow' is not defined

In [5]:
hello=tf.constant("Hello")
sess=tf.Session()
print(sess.run(hello))

b'Hello'


In [6]:
3 #랭크:0 tensor, shape:[]
[1,2,3] #랭크:1,  shape:[3]
[[1,2,3],[1,2,3]] #랭크:2, shape:[2,3]
[[[1,2,3]],[[4,5,6]]]
#랭크:3, shape:[2,1,3]

[[[1, 2, 3]], [[4, 5, 6]]]

In [7]:
a=tf.constant(10)
b=tf.constant(20)
sess=tf.Session()
#print(sess.run(tf.add(a,b)))
c=tf.add(a,b)
#print(sess.run(c))
#print(c)
print(sess.run(a))
print(sess.run(b))
print(sess.run([a,b]))
sess.close()

10
20
[10, 20]


In [8]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)
adderNode=a+b
sess=tf.Session()
print(sess.run(adderNode, feed_dict={a:[5,1],b:[3,2]}))
# print(sess.run(adderNode, feed_dict={a:1,b:2}))

[8. 3.]


In [9]:
# a=2, b=3
# =>5 * 3 => 15가 출력되도록 노드 정의
triple=adderNode*3 #구현
print(sess.run(triple,feed_dict={a:2, b:3}))



15.0


In [10]:
x=tf.placeholder(tf.float32,[None,3])
#print(x)
xdata=[[1,2,3],[4,5,6]]
#xdata2=[[1,2,3,4],[4,5,4,5]] 에러
print(sess.run(x, feed_dict={x:xdata}))
#print(sess.run(x, feed_dict={x:xdata2}))

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
#H(x)=wx+b
#w=tf.Variable(tf.random_normal([2,1]))
w=tf.Variable([[1],[2]])
#hf=tf.matmul(x,w)+b

In [12]:
xdata=[[1,2,3], #2행 3열(국어,영어,수학)
      [4,5,6]]
x=tf.placeholder(tf.float32, [None,3])
w=tf.Variable(
    tf.random_normal([3,1]))#각 과목 가중치
b=tf.Variable(
    tf.random_normal([1])) #편향
hf=tf.matmul(x,w)+b
sess=tf.Session()
# hf=xw+b
# hf실행
sess.run(tf.global_variables_initializer())
print(sess.run(hf,feed_dict={x:xdata}))
#x shape=>(2,3) * (3,1) => (2,1)
#w shape =>?

[[3.1124315]
 [6.8435454]]


In [13]:
#선형 회귀 모델

In [144]:
xtrain=[80, 95, 97] #모의고사 점수(3명)
ytrain=[82, 90, 98] #수능점수(3명)
#모의고사 70점 -> 수능?
#hf= x*w+b
#82=80*1+2
#90=95*0.9+1

In [145]:
w=tf.Variable(tf.random_normal([1]))
b=tf.Variable(tf.random_normal([1]))

In [146]:
hf=xtrain*w+b

In [147]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [148]:
print(sess.run([w,b,hf]))#[80, 95, 97]
#w=-0.35, b=0.49
#hf(예상)=[-27,-33,-33]    hf=xtrain*w+b
    #정답=[82, 90, 98]
#cost=((-27-82)^2+(-33-80)^2+(-33-98)^2))/3
#cost함수 미분 -> w, b업데이트(bp)

#w=0.35, b=0
#hf(예상)=[27,33,33]    hf=xtrain*w+b

[array([-1.0412021], dtype=float32), array([-1.1127023], dtype=float32), array([ -84.40887, -100.0269 , -102.1093 ], dtype=float32)]


In [149]:
#우리의 모델
hf=xtrain*w+b
cost=tf.reduce_mean(tf.square(hf-ytrain))
#(예상값-실제값)합의제곱에 대한 평균

In [150]:
opt=tf.train.GradientDescentOptimizer(0.00001)
train=opt.minimize(cost)

In [151]:
for step in range(2001):
    sess.run(train)
    if step%100==0:
        print(step, sess.run(cost),
             sess.run(w),sess.run(b))

0 24104.068 [-0.7026963] [-1.108992]
100 9.652096 [1.0031608] [-1.0900346]
200 9.652035 [1.0031579] [-1.0897604]
300 9.651948 [1.003155] [-1.0894862]
400 9.651885 [1.0031519] [-1.0892121]
500 9.651809 [1.0031489] [-1.0889379]
600 9.651733 [1.0031459] [-1.0886637]
700 9.651672 [1.003143] [-1.0883895]
800 9.651578 [1.0031399] [-1.0881153]
900 9.651519 [1.0031369] [-1.0878412]
1000 9.651443 [1.0031339] [-1.087567]
1100 9.651368 [1.0031309] [-1.0872928]
1200 9.651274 [1.0031278] [-1.0870186]
1300 9.651212 [1.0031248] [-1.0867444]
1400 9.651136 [1.0031219] [-1.0864702]
1500 9.651061 [1.0031189] [-1.0861961]
1600 9.651 [1.0031159] [-1.0859219]
1700 9.650906 [1.0031128] [-1.0856477]
1800 9.650829 [1.0031098] [-1.0853735]
1900 9.650755 [1.0031068] [-1.0850993]
2000 9.650694 [1.0031039] [-1.0848252]


In [154]:
wx+b
0.995*x-0.38

NameError: name 'wx' is not defined

In [155]:
#모의고사 점수가 50점 => 수능점수?
# sess.run(w)[0]
# sess.run(b)[0]
yhat=sess.run(w)[0]*50+sess.run(b)[0]
print("예상되는 수능점수는 ",yhat)

예상되는 수능점수는  49.07036745548248


In [ ]:
#car 데이터에서
#임의의 실린더 수(10, 12, 16)가 입력 -> hp?
#cost, w, b 출력
#cost 함수 시각화(w축)
#learning rate, training 조절