In [1]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

idx2code = {0:'c4', 1:'d4', 2:'e4', 3:'f4', 4:'g4', 5:'a4', 6:'b4',
            7:'c8', 8:'d8', 9:'e8', 10:'f8', 11:'g8', 12:'a8', 13:'b8'}

seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']


In [2]:
# pip install gTTs 설치 구글 음성 변형 서비스

In [3]:
from gtts import gTTS

In [4]:
text='Hi, everybody. Playing with TF is fun'
tts=gTTS(text=text, lang='en')
tts.save('hi.mp3')

In [5]:
text='안녕하세요. 여러분, 텐서플로우 재미있어요'
tts=gTTS(text=text, lang='ko')
tts.save('hiko.mp3')

In [6]:
texte='Hi, everybody. Playing with TF is fun'
tts=gTTS(text=texte, lang='en')
tts.save('hi.mp3')

In [7]:
textk='안녕하세요. 여러분, 텐서플로우 재미있어요'
tts=gTTS(text=textk, lang='ko')
tts.save('hiko.mp3')

In [8]:
ttsEn=gTTS(text=texte, lang='en')
ttsKr=gTTS(text=textk, lang='ko')

In [9]:
f=open("enkr.mp3",'wb')
ttsEn.write_to_fp(f)
ttsEn.write_to_fp(f)
ttsKr.write_to_fp(f)
f.close()

In [10]:
import numpy as np

In [11]:
len(seq)

54

In [12]:
def seq2dataset(seq, windowSize):
    dataset=[]
    for i in range(len(seq)-windowSize):#54-4=50
        subset=seq[i:(i+windowSize+1)]
        dataset.append([code2idx[item] for item in subset])
    return np.array(dataset)

In [13]:
print(seq2dataset(seq,windowSize=4))

[[11  9  2 10  8]
 [ 9  2 10  8  1]
 [ 2 10  8  1  7]
 [10  8  1  7  8]
 [ 8  1  7  8  9]
 [ 1  7  8  9 10]
 [ 7  8  9 10 11]
 [ 8  9 10 11 11]
 [ 9 10 11 11  4]
 [10 11 11  4 11]
 [11 11  4 11  9]
 [11  4 11  9  9]
 [ 4 11  9  9  9]
 [11  9  9  9 10]
 [ 9  9  9 10  8]
 [ 9  9 10  8  1]
 [ 9 10  8  1  7]
 [10  8  1  7  9]
 [ 8  1  7  9 11]
 [ 1  7  9 11 11]
 [ 7  9 11 11  9]
 [ 9 11 11  9  9]
 [11 11  9  9  2]
 [11  9  9  2  8]
 [ 9  9  2  8  8]
 [ 9  2  8  8  8]
 [ 2  8  8  8  8]
 [ 8  8  8  8  8]
 [ 8  8  8  8  9]
 [ 8  8  8  9  3]
 [ 8  8  9  3  9]
 [ 8  9  3  9  9]
 [ 9  3  9  9  9]
 [ 3  9  9  9  9]
 [ 9  9  9  9  9]
 [ 9  9  9  9 10]
 [ 9  9  9 10  4]
 [ 9  9 10  4 11]
 [ 9 10  4 11  9]
 [10  4 11  9  2]
 [ 4 11  9  2 10]
 [11  9  2 10  8]
 [ 9  2 10  8  1]
 [ 2 10  8  1  7]
 [10  8  1  7  9]
 [ 8  1  7  9 11]
 [ 1  7  9 11 11]
 [ 7  9 11 11  9]
 [ 9 11 11  9  9]
 [11 11  9  9  2]]


In [14]:
dataset=seq2dataset(seq,windowSize=4)
dataset.shape

(50, 5)

In [15]:
xTrain=dataset[:,0:4] # 나 비 야 나, ...
yTrain=dataset[:,4] # 비, ...
maxIdxValue=13

In [16]:
#입력값 정규화
xTrain=xTrain/maxIdxValue
xTrain

array([[0.84615385, 0.69230769, 0.15384615, 0.76923077],
       [0.69230769, 0.15384615, 0.76923077, 0.61538462],
       [0.15384615, 0.76923077, 0.61538462, 0.07692308],
       [0.76923077, 0.61538462, 0.07692308, 0.53846154],
       [0.61538462, 0.07692308, 0.53846154, 0.61538462],
       [0.07692308, 0.53846154, 0.61538462, 0.69230769],
       [0.53846154, 0.61538462, 0.69230769, 0.76923077],
       [0.61538462, 0.69230769, 0.76923077, 0.84615385],
       [0.69230769, 0.76923077, 0.84615385, 0.84615385],
       [0.76923077, 0.84615385, 0.84615385, 0.30769231],
       [0.84615385, 0.84615385, 0.30769231, 0.84615385],
       [0.84615385, 0.30769231, 0.84615385, 0.69230769],
       [0.30769231, 0.84615385, 0.69230769, 0.69230769],
       [0.84615385, 0.69230769, 0.69230769, 0.69230769],
       [0.69230769, 0.69230769, 0.69230769, 0.76923077],
       [0.69230769, 0.69230769, 0.76923077, 0.61538462],
       [0.69230769, 0.76923077, 0.61538462, 0.07692308],
       [0.76923077, 0.61538462,

In [17]:
from keras.utils import np_utils
yTrain=np_utils.to_categorical(yTrain)
yTrain.shape
#(50,)->(50,12)

Using TensorFlow backend.


(50, 12)

In [18]:
oneHotVecSize=yTrain.shape[1]#y:12가지 음계

In [19]:
from keras.models import Sequential
from keras.layers import Dense
import keras

In [20]:
#모델 생성
model=Sequential()
model.add(Dense(128, input_dim=4, activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(oneHotVecSize, activation='softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [21]:
model.summary()
# 128 * 4 + 128 =640
# 128 * 128 + 128 = 16512
# 128 * 12 + 128 = 1548

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 128)               640       
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 12)                1548      
Total params: 18,700
Trainable params: 18,700
Non-trainable params: 0
_________________________________________________________________


In [22]:
#모델 학습과정
model.compile(loss="categorical_crossentropy",optimizer='adam',
             metrics=['accuracy'])

In [23]:
class LossHistory(keras.callbacks.Callback):
    def init(self):
        self.losses=[]
        print("호출됨")
    def onEpochEnd(self, batch, logs={}):
        self.losses.append(logs.get('loss'))

In [24]:
history=LossHistory()
history.init()

호출됨


In [25]:
model.fit(xTrain,yTrain,epochs=2000,batch_size=10,callbacks=[history])



Epoch 1/2000
50/50 [==============================] - 0s 2ms/step - loss: 2.4169 - accuracy: 0.2400
Epoch 2/2000
50/50 [==============================] - 0s 121us/step - loss: 2.3202 - accuracy: 0.3200
Epoch 3/2000
50/50 [==============================] - 0s 160us/step - loss: 2.2205 - accuracy: 0.3400
Epoch 4/2000
50/50 [==============================] - 0s 120us/step - loss: 2.1360 - accuracy: 0.3400
Epoch 5/2000
50/50 [==============================] - 0s 140us/step - loss: 2.0384 - accuracy: 0.3400
Epoch 6/2000
50/50 [==============================] - 0s 100us/step - loss: 1.9668 - accuracy: 0.3400
Epoch 7/2000
50/50 [==============================] - 0s 140us/step - loss: 1.9251 - accuracy: 0.3400
Epoch 8/2000
50/50 [==============================] - 0s 120us/step - loss: 1.9011 - accuracy: 0.3400
Epoch 9/2000
50/50 [==============================] - 0s 161us/step - loss: 1.8753 - accuracy: 0.3400
Epoch 10/2000
50/50 [==============================] - 0s 120us/step - loss: 1.8563

50/50 [==============================] - 0s 120us/step - loss: 1.3886 - accuracy: 0.5800
Epoch 79/2000
50/50 [==============================] - 0s 120us/step - loss: 1.3866 - accuracy: 0.5400
Epoch 80/2000
50/50 [==============================] - 0s 100us/step - loss: 1.3786 - accuracy: 0.5400
Epoch 81/2000
50/50 [==============================] - 0s 120us/step - loss: 1.3861 - accuracy: 0.4800
Epoch 82/2000
50/50 [==============================] - 0s 140us/step - loss: 1.3787 - accuracy: 0.5000
Epoch 83/2000
50/50 [==============================] - 0s 120us/step - loss: 1.3725 - accuracy: 0.5400
Epoch 84/2000
50/50 [==============================] - 0s 100us/step - loss: 1.3722 - accuracy: 0.5200
Epoch 85/2000
50/50 [==============================] - 0s 100us/step - loss: 1.3661 - accuracy: 0.5400
Epoch 86/2000
50/50 [==============================] - 0s 120us/step - loss: 1.3627 - accuracy: 0.5600
Epoch 87/2000
50/50 [==============================] - 0s 120us/step - loss: 1.3595 - a

50/50 [==============================] - 0s 100us/step - loss: 1.1791 - accuracy: 0.6000
Epoch 158/2000
50/50 [==============================] - 0s 100us/step - loss: 1.1732 - accuracy: 0.6000
Epoch 159/2000
50/50 [==============================] - 0s 100us/step - loss: 1.1700 - accuracy: 0.5800
Epoch 160/2000
50/50 [==============================] - 0s 120us/step - loss: 1.1672 - accuracy: 0.5800
Epoch 161/2000
50/50 [==============================] - 0s 120us/step - loss: 1.1693 - accuracy: 0.5400
Epoch 162/2000
50/50 [==============================] - 0s 120us/step - loss: 1.1696 - accuracy: 0.5800
Epoch 163/2000
50/50 [==============================] - 0s 120us/step - loss: 1.1644 - accuracy: 0.5800
Epoch 164/2000
50/50 [==============================] - 0s 120us/step - loss: 1.1648 - accuracy: 0.6000
Epoch 165/2000
50/50 [==============================] - 0s 120us/step - loss: 1.1592 - accuracy: 0.5800
Epoch 166/2000
50/50 [==============================] - 0s 120us/step - loss: 1

50/50 [==============================] - 0s 120us/step - loss: 1.0264 - accuracy: 0.5800
Epoch 236/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0160 - accuracy: 0.5800
Epoch 237/2000
50/50 [==============================] - 0s 140us/step - loss: 1.0150 - accuracy: 0.5800
Epoch 238/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0141 - accuracy: 0.5800
Epoch 239/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0162 - accuracy: 0.5800
Epoch 240/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0124 - accuracy: 0.5800
Epoch 241/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0038 - accuracy: 0.5800
Epoch 242/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0088 - accuracy: 0.5800
Epoch 243/2000
50/50 [==============================] - 0s 120us/step - loss: 1.0079 - accuracy: 0.5800
Epoch 244/2000
50/50 [==============================] - 0s 120us/step - loss: 1

50/50 [==============================] - 0s 120us/step - loss: 0.8850 - accuracy: 0.6000
Epoch 314/2000
50/50 [==============================] - 0s 120us/step - loss: 0.8839 - accuracy: 0.6000
Epoch 315/2000
50/50 [==============================] - ETA: 0s - loss: 0.8072 - accuracy: 0.50 - 0s 120us/step - loss: 0.9027 - accuracy: 0.6200
Epoch 316/2000
50/50 [==============================] - 0s 100us/step - loss: 0.8801 - accuracy: 0.6000
Epoch 317/2000
50/50 [==============================] - 0s 140us/step - loss: 0.8867 - accuracy: 0.6000
Epoch 318/2000
50/50 [==============================] - 0s 120us/step - loss: 0.8790 - accuracy: 0.6400
Epoch 319/2000
50/50 [==============================] - 0s 120us/step - loss: 0.8816 - accuracy: 0.6200
Epoch 320/2000
50/50 [==============================] - 0s 140us/step - loss: 0.8834 - accuracy: 0.6200
Epoch 321/2000
50/50 [==============================] - 0s 120us/step - loss: 0.8735 - accuracy: 0.6000
Epoch 322/2000
50/50 [===============

50/50 [==============================] - 0s 120us/step - loss: 0.7796 - accuracy: 0.6600
Epoch 392/2000
50/50 [==============================] - 0s 120us/step - loss: 0.7665 - accuracy: 0.6600
Epoch 393/2000
50/50 [==============================] - 0s 100us/step - loss: 0.7649 - accuracy: 0.7200
Epoch 394/2000
50/50 [==============================] - 0s 120us/step - loss: 0.7608 - accuracy: 0.7200
Epoch 395/2000
50/50 [==============================] - 0s 120us/step - loss: 0.7616 - accuracy: 0.6800
Epoch 396/2000
50/50 [==============================] - 0s 120us/step - loss: 0.7620 - accuracy: 0.6600
Epoch 397/2000
50/50 [==============================] - 0s 120us/step - loss: 0.7572 - accuracy: 0.6800
Epoch 398/2000
50/50 [==============================] - 0s 100us/step - loss: 0.7572 - accuracy: 0.7200
Epoch 399/2000
50/50 [==============================] - 0s 120us/step - loss: 0.7518 - accuracy: 0.7200
Epoch 400/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 100us/step - loss: 0.6636 - accuracy: 0.7600
Epoch 470/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6559 - accuracy: 0.7600
Epoch 471/2000
50/50 [==============================] - 0s 100us/step - loss: 0.6583 - accuracy: 0.7400
Epoch 472/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6613 - accuracy: 0.7600
Epoch 473/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6652 - accuracy: 0.7600
Epoch 474/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6568 - accuracy: 0.7600
Epoch 475/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6640 - accuracy: 0.7200
Epoch 476/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6558 - accuracy: 0.7600
Epoch 477/2000
50/50 [==============================] - 0s 120us/step - loss: 0.6517 - accuracy: 0.7800
Epoch 478/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 120us/step - loss: 0.5706 - accuracy: 0.8000
Epoch 548/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5659 - accuracy: 0.8200
Epoch 549/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5602 - accuracy: 0.8200
Epoch 550/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5643 - accuracy: 0.8200
Epoch 551/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5679 - accuracy: 0.8200
Epoch 552/2000
50/50 [==============================] - 0s 100us/step - loss: 0.5609 - accuracy: 0.8200
Epoch 553/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5644 - accuracy: 0.8200
Epoch 554/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5665 - accuracy: 0.8000
Epoch 555/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5622 - accuracy: 0.8200
Epoch 556/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 100us/step - loss: 0.4995 - accuracy: 0.8600
Epoch 626/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4872 - accuracy: 0.8800
Epoch 627/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5093 - accuracy: 0.8000
Epoch 628/2000
50/50 [==============================] - 0s 100us/step - loss: 0.4906 - accuracy: 0.8400
Epoch 629/2000
50/50 [==============================] - 0s 100us/step - loss: 0.4886 - accuracy: 0.8400
Epoch 630/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4871 - accuracy: 0.8600
Epoch 631/2000
50/50 [==============================] - 0s 120us/step - loss: 0.5042 - accuracy: 0.8400
Epoch 632/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4848 - accuracy: 0.8000
Epoch 633/2000
50/50 [==============================] - 0s 100us/step - loss: 0.5062 - accuracy: 0.8600
Epoch 634/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 120us/step - loss: 0.4366 - accuracy: 0.8800
Epoch 704/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4249 - accuracy: 0.8400
Epoch 705/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4348 - accuracy: 0.8800
Epoch 706/2000
50/50 [==============================] - 0s 140us/step - loss: 0.4331 - accuracy: 0.9000
Epoch 707/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4270 - accuracy: 0.8800
Epoch 708/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4270 - accuracy: 0.8800
Epoch 709/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4225 - accuracy: 0.8800
Epoch 710/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4268 - accuracy: 0.8800
Epoch 711/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4222 - accuracy: 0.8800
Epoch 712/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 120us/step - loss: 0.3834 - accuracy: 0.8800
Epoch 782/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3862 - accuracy: 0.8800
Epoch 783/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3831 - accuracy: 0.8400
Epoch 784/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3932 - accuracy: 0.8400
Epoch 785/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3935 - accuracy: 0.8800
Epoch 786/2000
50/50 [==============================] - 0s 100us/step - loss: 0.3846 - accuracy: 0.8800
Epoch 787/2000
50/50 [==============================] - 0s 120us/step - loss: 0.4009 - accuracy: 0.8800
Epoch 788/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3849 - accuracy: 0.8800
Epoch 789/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3802 - accuracy: 0.8800
Epoch 790/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 100us/step - loss: 0.3554 - accuracy: 0.8800
Epoch 860/2000
50/50 [==============================] - 0s 100us/step - loss: 0.3442 - accuracy: 0.9000
Epoch 861/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3423 - accuracy: 0.9200
Epoch 862/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3370 - accuracy: 0.9200
Epoch 863/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3451 - accuracy: 0.9200
Epoch 864/2000
50/50 [==============================] - 0s 100us/step - loss: 0.3489 - accuracy: 0.8800
Epoch 865/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3504 - accuracy: 0.8800
Epoch 866/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3552 - accuracy: 0.9000
Epoch 867/2000
50/50 [==============================] - 0s 100us/step - loss: 0.3428 - accuracy: 0.9200
Epoch 868/2000
50/50 [==============================] - 0s 120us/step - loss: 0

50/50 [==============================] - 0s 120us/step - loss: 0.3121 - accuracy: 0.9200
Epoch 938/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3124 - accuracy: 0.9000
Epoch 939/2000
50/50 [==============================] - 0s 140us/step - loss: 0.3102 - accuracy: 0.9200
Epoch 940/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3115 - accuracy: 0.9200
Epoch 941/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3092 - accuracy: 0.9000
Epoch 942/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3178 - accuracy: 0.9200
Epoch 943/2000
50/50 [==============================] - 0s 140us/step - loss: 0.3037 - accuracy: 0.9200
Epoch 944/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3011 - accuracy: 0.9200
Epoch 945/2000
50/50 [==============================] - 0s 120us/step - loss: 0.3295 - accuracy: 0.9000
Epoch 946/2000
50/50 [==============================] - 0s 100us/step - loss: 0

50/50 [==============================] - 0s 140us/step - loss: 0.2802 - accuracy: 0.9200
Epoch 1016/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2854 - accuracy: 0.9200
Epoch 1017/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2892 - accuracy: 0.9000
Epoch 1018/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2852 - accuracy: 0.9200
Epoch 1019/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2892 - accuracy: 0.9200
Epoch 1020/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2871 - accuracy: 0.9200
Epoch 1021/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2756 - accuracy: 0.9200
Epoch 1022/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2814 - accuracy: 0.9000
Epoch 1023/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2778 - accuracy: 0.9200
Epoch 1024/2000
50/50 [==============================] - 0s 100us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.2740 - accuracy: 0.9000
Epoch 1093/2000
50/50 [==============================] - 0s 100us/step - loss: 0.2532 - accuracy: 0.9400
Epoch 1094/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2645 - accuracy: 0.9200
Epoch 1095/2000
50/50 [==============================] - 0s 100us/step - loss: 0.2628 - accuracy: 0.9000
Epoch 1096/2000
50/50 [==============================] - 0s 100us/step - loss: 0.2690 - accuracy: 0.9000
Epoch 1097/2000
50/50 [==============================] - 0s 100us/step - loss: 0.2533 - accuracy: 0.9200
Epoch 1098/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2581 - accuracy: 0.9200
Epoch 1099/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2635 - accuracy: 0.9000
Epoch 1100/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2607 - accuracy: 0.9000
Epoch 1101/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.2383 - accuracy: 0.9200
Epoch 1171/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2420 - accuracy: 0.9200
Epoch 1172/2000
50/50 [==============================] - 0s 100us/step - loss: 0.2483 - accuracy: 0.8800
Epoch 1173/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2367 - accuracy: 0.9000
Epoch 1174/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2392 - accuracy: 0.9200
Epoch 1175/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2402 - accuracy: 0.9200
Epoch 1176/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2389 - accuracy: 0.9200
Epoch 1177/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2367 - accuracy: 0.9000
Epoch 1178/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2454 - accuracy: 0.9200
Epoch 1179/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.2210 - accuracy: 0.9200
Epoch 1249/2000
50/50 [==============================] - 0s 140us/step - loss: 0.2221 - accuracy: 0.9200
Epoch 1250/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2302 - accuracy: 0.9200
Epoch 1251/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2189 - accuracy: 0.9200
Epoch 1252/2000
50/50 [==============================] - 0s 140us/step - loss: 0.2281 - accuracy: 0.9200
Epoch 1253/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2299 - accuracy: 0.9000
Epoch 1254/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2314 - accuracy: 0.8800
Epoch 1255/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2281 - accuracy: 0.9200
Epoch 1256/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2227 - accuracy: 0.9000
Epoch 1257/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 100us/step - loss: 0.2101 - accuracy: 0.9200
Epoch 1326/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2152 - accuracy: 0.9000
Epoch 1327/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2236 - accuracy: 0.9200
Epoch 1328/2000
50/50 [==============================] - 0s 140us/step - loss: 0.2162 - accuracy: 0.9000
Epoch 1329/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2091 - accuracy: 0.9200
Epoch 1330/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2198 - accuracy: 0.9200
Epoch 1331/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2113 - accuracy: 0.9000
Epoch 1332/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2159 - accuracy: 0.9000
Epoch 1333/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2096 - accuracy: 0.9400
Epoch 1334/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.2133 - accuracy: 0.8800
Epoch 1404/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2168 - accuracy: 0.9000
Epoch 1405/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2032 - accuracy: 0.9000
Epoch 1406/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2028 - accuracy: 0.9200
Epoch 1407/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2076 - accuracy: 0.9000
Epoch 1408/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2113 - accuracy: 0.9200
Epoch 1409/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2061 - accuracy: 0.8800
Epoch 1410/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2058 - accuracy: 0.9200
Epoch 1411/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1998 - accuracy: 0.9000
Epoch 1412/2000
50/50 [==============================] - 0s 100us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.1881 - accuracy: 0.9000
Epoch 1482/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2244 - accuracy: 0.9200
Epoch 1483/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1962 - accuracy: 0.9000
Epoch 1484/2000
50/50 [==============================] - 0s 120us/step - loss: 0.2093 - accuracy: 0.9000
Epoch 1485/2000
50/50 [==============================] - ETA: 0s - loss: 0.5125 - accuracy: 0.80 - 0s 120us/step - loss: 0.1995 - accuracy: 0.9200
Epoch 1486/2000
50/50 [==============================] - 0s 140us/step - loss: 0.2066 - accuracy: 0.9200
Epoch 1487/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1939 - accuracy: 0.8800
Epoch 1488/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1938 - accuracy: 0.8800
Epoch 1489/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1978 - accuracy: 0.9200
Epoch 1490/2000
50/50 [======

50/50 [==============================] - 0s 100us/step - loss: 0.1796 - accuracy: 0.9200
Epoch 1559/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1768 - accuracy: 0.9000
Epoch 1560/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1730 - accuracy: 0.9200
Epoch 1561/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1970 - accuracy: 0.9200
Epoch 1562/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1810 - accuracy: 0.9000
Epoch 1563/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1826 - accuracy: 0.9000
Epoch 1564/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1783 - accuracy: 0.9200
Epoch 1565/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1821 - accuracy: 0.9200
Epoch 1566/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1878 - accuracy: 0.8800
Epoch 1567/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.1788 - accuracy: 0.9200
Epoch 1636/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1724 - accuracy: 0.9200
Epoch 1637/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1764 - accuracy: 0.9000
Epoch 1638/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1774 - accuracy: 0.9200
Epoch 1639/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1717 - accuracy: 0.9200
Epoch 1640/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1776 - accuracy: 0.9000
Epoch 1641/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1704 - accuracy: 0.9200
Epoch 1642/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1713 - accuracy: 0.9000
Epoch 1643/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1718 - accuracy: 0.9200
Epoch 1644/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 140us/step - loss: 0.1833 - accuracy: 0.9000
Epoch 1714/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1842 - accuracy: 0.8800
Epoch 1715/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1885 - accuracy: 0.8600
Epoch 1716/2000
50/50 [==============================] - 0s 140us/step - loss: 0.1707 - accuracy: 0.9000
Epoch 1717/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1737 - accuracy: 0.8800
Epoch 1718/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1714 - accuracy: 0.9200
Epoch 1719/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1775 - accuracy: 0.9000
Epoch 1720/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1724 - accuracy: 0.9200
Epoch 1721/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1621 - accuracy: 0.9200
Epoch 1722/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.1696 - accuracy: 0.9000
Epoch 1791/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1715 - accuracy: 0.9000
Epoch 1792/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1703 - accuracy: 0.9000
Epoch 1793/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1943 - accuracy: 0.8400
Epoch 1794/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1685 - accuracy: 0.9000
Epoch 1795/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1811 - accuracy: 0.8800
Epoch 1796/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1666 - accuracy: 0.9200
Epoch 1797/2000
50/50 [==============================] - 0s 100us/step - loss: 0.1657 - accuracy: 0.9000
Epoch 1798/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1581 - accuracy: 0.9400
Epoch 1799/2000
50/50 [==============================] - 0s 100us/step 

50/50 [==============================] - 0s 140us/step - loss: 0.1686 - accuracy: 0.9000
Epoch 1868/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1573 - accuracy: 0.9200
Epoch 1869/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1649 - accuracy: 0.9000
Epoch 1870/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1572 - accuracy: 0.9200
Epoch 1871/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1541 - accuracy: 0.9200
Epoch 1872/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1531 - accuracy: 0.9200
Epoch 1873/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1566 - accuracy: 0.9200
Epoch 1874/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1664 - accuracy: 0.9200
Epoch 1875/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1593 - accuracy: 0.9200
Epoch 1876/2000
50/50 [==============================] - 0s 120us/step 

50/50 [==============================] - 0s 120us/step - loss: 0.1632 - accuracy: 0.9000
Epoch 1945/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1538 - accuracy: 0.9200
Epoch 1946/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1503 - accuracy: 0.9000
Epoch 1947/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1560 - accuracy: 0.9200
Epoch 1948/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1642 - accuracy: 0.9000
Epoch 1949/2000
50/50 [==============================] - 0s 140us/step - loss: 0.1548 - accuracy: 0.9000
Epoch 1950/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1563 - accuracy: 0.9000
Epoch 1951/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1590 - accuracy: 0.9200
Epoch 1952/2000
50/50 [==============================] - 0s 120us/step - loss: 0.1468 - accuracy: 0.9200
Epoch 1953/2000
50/50 [==============================] - 0s 120us/step 

In [26]:
import matplotlib.pyplot as plt

In [27]:
plt.plot(history.logissess)
plt.ylabel('loss')
plt.xlabel('epoch')
plt.show()

AttributeError: 'LossHistory' object has no attribute 'logissess'

In [28]:
scores=model.evaluate(xTrain,yTrain)
print("%s:%.2f%%" %(model.metrics_names[1],scores[1]*100))

50/50 [==============================] - 0s 480us/step
accuracy:92.00%


In [29]:
seqOut=['g8','e8','e4','f8']
predOut=model.predict(xTrain)

In [30]:
predOut.shape # 50,12

(50, 12)

In [31]:
predCount=50
for i in range(predCount):
    idx=np.argmax(predOut[i])
    seqOut.append(idx2code[idx])
print(seqOut)

['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'e8', 'f8', 'g8', 'g8', 'g4', 'g8', 'e8', 'e8', 'e8', 'f8', 'g4', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4', 'd8', 'd8', 'd8', 'd8', 'e8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'g4', 'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']


In [32]:
from pygame import mixer

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


In [33]:
mixer.init()
mixer.music.load("sound1.mp3")
#https://www.pygame.org/docs/

error: DirectSoundCreate: No audio device found

In [34]:
#곡 전체 예측
seqIn=['g8','e8','e4','f8']
seqOut=seqIn
seqIn=[code2idx[it]/float(maxIdxValue) for it in seqIn]
print(np.shape(seqIn))

(4,)


In [35]:
for i in range(predCount):
    seqIn2=np.array(seqIn)#[0.13,...]
    seqIn2=np.reshape(seqIn2,(1,4))#1:batchsize
    model.predict(seqIn2)
    predOut=model.predict(seqIn2)
    idx=np.argmax(predOut)
    seqOut.append(idx2code[idx])
    seqIn.append(idx/float(maxIdxValue))
    seqIn.pop(0)
print(seqOut)

['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8', 'e8']


In [36]:
from keras.layers import LSTM
model=Sequential()
model.add(LSTM(128, input_shape=(4,1)))
#128출력셀, 4타임스텝, 1 속성개수
#stateful=기본값이 False, 여기서는 True로 해주어야 함.
model.add(Dense(oneHotVecSize, activation='softmax'))
"""
타임스텝(windwo size):샘플 1개에 포함된 시퀀스 개수(input size)
속성:입력되는 음표 1개당 index 1개 입력

"""

'\n타임스텝(windwo size):샘플 1개에 포함된 시퀀스 개수(input size)\n속성:입력되는 음표 1개당 index 1개 입력\n\n'

In [37]:
np.shape(xTrain)#샘플수, 타임스탭, 속성수
xTrain=np.reshape(xTrain,(50,4,1))

In [38]:
#모델 학습과정
model.compile(loss="categorical_crossentropy",optimizer='adam',
             metrics=['accuracy'])

In [39]:
model.fit(xTrain,yTrain,epochs=2000,batch_size=14,callbacks=[history])

Epoch 1/2000
50/50 [==============================] - 0s 4ms/step - loss: 2.4921 - accuracy: 0.1600
Epoch 2/2000
50/50 [==============================] - 0s 340us/step - loss: 2.4516 - accuracy: 0.1600
Epoch 3/2000
50/50 [==============================] - 0s 340us/step - loss: 2.4084 - accuracy: 0.3000
Epoch 4/2000
50/50 [==============================] - 0s 341us/step - loss: 2.3619 - accuracy: 0.3400
Epoch 5/2000
50/50 [==============================] - 0s 340us/step - loss: 2.3137 - accuracy: 0.3400
Epoch 6/2000
50/50 [==============================] - 0s 320us/step - loss: 2.2485 - accuracy: 0.3400
Epoch 7/2000
50/50 [==============================] - 0s 320us/step - loss: 2.1797 - accuracy: 0.3400
Epoch 8/2000
50/50 [==============================] - 0s 300us/step - loss: 2.0849 - accuracy: 0.3400
Epoch 9/2000
50/50 [==============================] - 0s 300us/step - loss: 2.0174 - accuracy: 0.3400
Epoch 10/2000
50/50 [==============================] - 0s 300us/step - loss: 1.9659 

50/50 [==============================] - 0s 340us/step - loss: 1.8296 - accuracy: 0.3400
Epoch 81/2000
50/50 [==============================] - 0s 320us/step - loss: 1.8278 - accuracy: 0.3400
Epoch 82/2000
50/50 [==============================] - 0s 300us/step - loss: 1.8268 - accuracy: 0.3400
Epoch 83/2000
50/50 [==============================] - 0s 340us/step - loss: 1.8259 - accuracy: 0.3400
Epoch 84/2000
50/50 [==============================] - 0s 320us/step - loss: 1.8236 - accuracy: 0.3400
Epoch 85/2000
50/50 [==============================] - 0s 320us/step - loss: 1.8232 - accuracy: 0.3400
Epoch 86/2000
50/50 [==============================] - 0s 300us/step - loss: 1.8213 - accuracy: 0.3400
Epoch 87/2000
50/50 [==============================] - 0s 300us/step - loss: 1.8133 - accuracy: 0.3400
Epoch 88/2000
50/50 [==============================] - 0s 300us/step - loss: 1.8114 - accuracy: 0.3400
Epoch 89/2000
50/50 [==============================] - 0s 340us/step - loss: 1.8119 - a

50/50 [==============================] - 0s 320us/step - loss: 1.5496 - accuracy: 0.4600
Epoch 160/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5462 - accuracy: 0.4400
Epoch 161/2000
50/50 [==============================] - 0s 340us/step - loss: 1.5428 - accuracy: 0.4600
Epoch 162/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5572 - accuracy: 0.4800
Epoch 163/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5382 - accuracy: 0.4600
Epoch 164/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5400 - accuracy: 0.4800
Epoch 165/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5387 - accuracy: 0.4600
Epoch 166/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5366 - accuracy: 0.4400
Epoch 167/2000
50/50 [==============================] - 0s 320us/step - loss: 1.5248 - accuracy: 0.4400
Epoch 168/2000
50/50 [==============================] - 0s 300us/step - loss: 1

50/50 [==============================] - 0s 300us/step - loss: 1.3812 - accuracy: 0.5600
Epoch 238/2000
50/50 [==============================] - 0s 320us/step - loss: 1.3803 - accuracy: 0.5400
Epoch 239/2000
50/50 [==============================] - 0s 340us/step - loss: 1.3665 - accuracy: 0.5600
Epoch 240/2000
50/50 [==============================] - 0s 320us/step - loss: 1.3761 - accuracy: 0.5600
Epoch 241/2000
50/50 [==============================] - 0s 320us/step - loss: 1.3688 - accuracy: 0.5400
Epoch 242/2000
50/50 [==============================] - 0s 320us/step - loss: 1.3824 - accuracy: 0.5200
Epoch 243/2000
50/50 [==============================] - 0s 300us/step - loss: 1.3625 - accuracy: 0.5400
Epoch 244/2000
50/50 [==============================] - 0s 340us/step - loss: 1.3665 - accuracy: 0.5400
Epoch 245/2000
50/50 [==============================] - 0s 320us/step - loss: 1.3791 - accuracy: 0.5800
Epoch 246/2000
50/50 [==============================] - 0s 320us/step - loss: 1

50/50 [==============================] - 0s 340us/step - loss: 1.2415 - accuracy: 0.5000
Epoch 316/2000
50/50 [==============================] - 0s 320us/step - loss: 1.2423 - accuracy: 0.5600
Epoch 317/2000
50/50 [==============================] - 0s 320us/step - loss: 1.2354 - accuracy: 0.5400
Epoch 318/2000
50/50 [==============================] - 0s 320us/step - loss: 1.2369 - accuracy: 0.4800
Epoch 319/2000
50/50 [==============================] - 0s 300us/step - loss: 1.2489 - accuracy: 0.4600
Epoch 320/2000
50/50 [==============================] - 0s 300us/step - loss: 1.2436 - accuracy: 0.5800
Epoch 321/2000
50/50 [==============================] - 0s 300us/step - loss: 1.2404 - accuracy: 0.5600
Epoch 322/2000
50/50 [==============================] - 0s 300us/step - loss: 1.2460 - accuracy: 0.5000
Epoch 323/2000
50/50 [==============================] - 0s 320us/step - loss: 1.2271 - accuracy: 0.5400
Epoch 324/2000
50/50 [==============================] - 0s 320us/step - loss: 1

50/50 [==============================] - 0s 320us/step - loss: 1.1090 - accuracy: 0.5600
Epoch 394/2000
50/50 [==============================] - 0s 320us/step - loss: 1.0862 - accuracy: 0.5800
Epoch 395/2000
50/50 [==============================] - 0s 320us/step - loss: 1.0821 - accuracy: 0.5600
Epoch 396/2000
50/50 [==============================] - 0s 320us/step - loss: 1.0805 - accuracy: 0.6000
Epoch 397/2000
50/50 [==============================] - 0s 320us/step - loss: 1.1315 - accuracy: 0.5600
Epoch 398/2000
50/50 [==============================] - 0s 320us/step - loss: 1.0952 - accuracy: 0.6000
Epoch 399/2000
50/50 [==============================] - 0s 320us/step - loss: 1.1059 - accuracy: 0.5600
Epoch 400/2000
50/50 [==============================] - 0s 320us/step - loss: 1.1392 - accuracy: 0.5400
Epoch 401/2000
50/50 [==============================] - 0s 320us/step - loss: 1.1007 - accuracy: 0.5800
Epoch 402/2000
50/50 [==============================] - 0s 320us/step - loss: 1

50/50 [==============================] - 0s 300us/step - loss: 0.9256 - accuracy: 0.6000
Epoch 472/2000
50/50 [==============================] - 0s 300us/step - loss: 0.9307 - accuracy: 0.6200
Epoch 473/2000
50/50 [==============================] - 0s 320us/step - loss: 0.9273 - accuracy: 0.6400
Epoch 474/2000
50/50 [==============================] - 0s 320us/step - loss: 0.9271 - accuracy: 0.6000
Epoch 475/2000
50/50 [==============================] - 0s 320us/step - loss: 0.9219 - accuracy: 0.6200
Epoch 476/2000
50/50 [==============================] - 0s 320us/step - loss: 0.9159 - accuracy: 0.6000
Epoch 477/2000
50/50 [==============================] - 0s 300us/step - loss: 0.9189 - accuracy: 0.6000
Epoch 478/2000
50/50 [==============================] - 0s 300us/step - loss: 0.9096 - accuracy: 0.6400
Epoch 479/2000
50/50 [==============================] - 0s 320us/step - loss: 0.9163 - accuracy: 0.6400
Epoch 480/2000
50/50 [==============================] - 0s 320us/step - loss: 0

50/50 [==============================] - 0s 320us/step - loss: 0.8007 - accuracy: 0.6200
Epoch 550/2000
50/50 [==============================] - 0s 340us/step - loss: 0.8259 - accuracy: 0.6800
Epoch 551/2000
50/50 [==============================] - 0s 340us/step - loss: 0.8152 - accuracy: 0.6400
Epoch 552/2000
50/50 [==============================] - 0s 320us/step - loss: 0.7878 - accuracy: 0.6800
Epoch 553/2000
50/50 [==============================] - 0s 340us/step - loss: 0.7977 - accuracy: 0.6600
Epoch 554/2000
50/50 [==============================] - 0s 340us/step - loss: 0.8149 - accuracy: 0.6600
Epoch 555/2000
50/50 [==============================] - 0s 340us/step - loss: 0.7816 - accuracy: 0.7000
Epoch 556/2000
50/50 [==============================] - 0s 320us/step - loss: 0.8254 - accuracy: 0.6600
Epoch 557/2000
50/50 [==============================] - 0s 340us/step - loss: 0.8129 - accuracy: 0.6400
Epoch 558/2000
50/50 [==============================] - 0s 340us/step - loss: 0

50/50 [==============================] - 0s 320us/step - loss: 0.7550 - accuracy: 0.7200
Epoch 628/2000
50/50 [==============================] - 0s 340us/step - loss: 0.7619 - accuracy: 0.7600
Epoch 629/2000
50/50 [==============================] - 0s 320us/step - loss: 0.7219 - accuracy: 0.6600
Epoch 630/2000
50/50 [==============================] - 0s 320us/step - loss: 0.7483 - accuracy: 0.7000
Epoch 631/2000
50/50 [==============================] - 0s 320us/step - loss: 0.7233 - accuracy: 0.6600
Epoch 632/2000
50/50 [==============================] - 0s 320us/step - loss: 0.7101 - accuracy: 0.7200
Epoch 633/2000
50/50 [==============================] - 0s 300us/step - loss: 0.7046 - accuracy: 0.7400
Epoch 634/2000
50/50 [==============================] - 0s 340us/step - loss: 0.7006 - accuracy: 0.7200
Epoch 635/2000
50/50 [==============================] - 0s 300us/step - loss: 0.7000 - accuracy: 0.7200
Epoch 636/2000
50/50 [==============================] - 0s 320us/step - loss: 0

50/50 [==============================] - 0s 320us/step - loss: 0.6355 - accuracy: 0.7600
Epoch 706/2000
50/50 [==============================] - 0s 340us/step - loss: 0.6450 - accuracy: 0.7400
Epoch 707/2000
50/50 [==============================] - 0s 320us/step - loss: 0.6253 - accuracy: 0.7800
Epoch 708/2000
50/50 [==============================] - 0s 280us/step - loss: 0.6198 - accuracy: 0.7800
Epoch 709/2000
50/50 [==============================] - 0s 320us/step - loss: 0.6219 - accuracy: 0.7400
Epoch 710/2000
50/50 [==============================] - 0s 320us/step - loss: 0.6230 - accuracy: 0.7400
Epoch 711/2000
50/50 [==============================] - 0s 320us/step - loss: 0.6299 - accuracy: 0.8200
Epoch 712/2000
50/50 [==============================] - 0s 320us/step - loss: 0.6101 - accuracy: 0.8000
Epoch 713/2000
50/50 [==============================] - 0s 320us/step - loss: 0.6220 - accuracy: 0.7600
Epoch 714/2000
50/50 [==============================] - 0s 300us/step - loss: 0

50/50 [==============================] - 0s 320us/step - loss: 0.5734 - accuracy: 0.7800
Epoch 784/2000
50/50 [==============================] - 0s 300us/step - loss: 0.5759 - accuracy: 0.7800
Epoch 785/2000
50/50 [==============================] - 0s 300us/step - loss: 0.5647 - accuracy: 0.8200
Epoch 786/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5750 - accuracy: 0.8000
Epoch 787/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5631 - accuracy: 0.8400
Epoch 788/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5697 - accuracy: 0.8000
Epoch 789/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5573 - accuracy: 0.8000
Epoch 790/2000
50/50 [==============================] - 0s 300us/step - loss: 0.5554 - accuracy: 0.7800
Epoch 791/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5702 - accuracy: 0.7800
Epoch 792/2000
50/50 [==============================] - 0s 300us/step - loss: 0

50/50 [==============================] - 0s 320us/step - loss: 0.5155 - accuracy: 0.8200
Epoch 862/2000
50/50 [==============================] - ETA: 0s - loss: 0.5220 - accuracy: 0.71 - 0s 320us/step - loss: 0.5375 - accuracy: 0.7800
Epoch 863/2000
50/50 [==============================] - 0s 300us/step - loss: 0.5376 - accuracy: 0.8200
Epoch 864/2000
50/50 [==============================] - 0s 340us/step - loss: 0.5147 - accuracy: 0.8200
Epoch 865/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5342 - accuracy: 0.8000
Epoch 866/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5356 - accuracy: 0.8400
Epoch 867/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5356 - accuracy: 0.8000
Epoch 868/2000
50/50 [==============================] - 0s 300us/step - loss: 0.5343 - accuracy: 0.8200
Epoch 869/2000
50/50 [==============================] - 0s 320us/step - loss: 0.5226 - accuracy: 0.8200
Epoch 870/2000
50/50 [===============

50/50 [==============================] - 0s 302us/step - loss: 0.4786 - accuracy: 0.8600
Epoch 940/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4870 - accuracy: 0.8400
Epoch 941/2000
50/50 [==============================] - 0s 340us/step - loss: 0.4943 - accuracy: 0.8000
Epoch 942/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4899 - accuracy: 0.8600
Epoch 943/2000
50/50 [==============================] - 0s 340us/step - loss: 0.4764 - accuracy: 0.8600
Epoch 944/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4847 - accuracy: 0.8400
Epoch 945/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4826 - accuracy: 0.8400
Epoch 946/2000
50/50 [==============================] - 0s 300us/step - loss: 0.5010 - accuracy: 0.8200
Epoch 947/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4749 - accuracy: 0.8400
Epoch 948/2000
50/50 [==============================] - 0s 320us/step - loss: 0

50/50 [==============================] - 0s 320us/step - loss: 0.4482 - accuracy: 0.8200
Epoch 1018/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4459 - accuracy: 0.8600
Epoch 1019/2000
50/50 [==============================] - 0s 340us/step - loss: 0.4735 - accuracy: 0.8600
Epoch 1020/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4684 - accuracy: 0.8200
Epoch 1021/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4570 - accuracy: 0.8400
Epoch 1022/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4688 - accuracy: 0.8200
Epoch 1023/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4676 - accuracy: 0.8200
Epoch 1024/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4552 - accuracy: 0.8200
Epoch 1025/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4995 - accuracy: 0.8200
Epoch 1026/2000
50/50 [==============================] - 0s 340us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.4361 - accuracy: 0.8400
Epoch 1096/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4311 - accuracy: 0.8400
Epoch 1097/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4331 - accuracy: 0.8600
Epoch 1098/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4236 - accuracy: 0.8600
Epoch 1099/2000
50/50 [==============================] - 0s 360us/step - loss: 0.4251 - accuracy: 0.8400
Epoch 1100/2000
50/50 [==============================] - 0s 360us/step - loss: 0.4359 - accuracy: 0.8600
Epoch 1101/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4114 - accuracy: 0.8600
Epoch 1102/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4464 - accuracy: 0.8200
Epoch 1103/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4322 - accuracy: 0.8400
Epoch 1104/2000
50/50 [==============================] - 0s 340us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.4079 - accuracy: 0.8600
Epoch 1173/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4107 - accuracy: 0.8600
Epoch 1174/2000
50/50 [==============================] - 0s 280us/step - loss: 0.4006 - accuracy: 0.8600
Epoch 1175/2000
50/50 [==============================] - 0s 340us/step - loss: 0.4067 - accuracy: 0.8600
Epoch 1176/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4014 - accuracy: 0.8600
Epoch 1177/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4002 - accuracy: 0.8600
Epoch 1178/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3993 - accuracy: 0.8600
Epoch 1179/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4013 - accuracy: 0.8600
Epoch 1180/2000
50/50 [==============================] - 0s 340us/step - loss: 0.4252 - accuracy: 0.8200
Epoch 1181/2000
50/50 [==============================] - 0s 360us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.3883 - accuracy: 0.8600
Epoch 1251/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3934 - accuracy: 0.8600
Epoch 1252/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3779 - accuracy: 0.8800
Epoch 1253/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3964 - accuracy: 0.8600
Epoch 1254/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3910 - accuracy: 0.8600
Epoch 1255/2000
50/50 [==============================] - 0s 300us/step - loss: 0.4238 - accuracy: 0.8400
Epoch 1256/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3966 - accuracy: 0.8600
Epoch 1257/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4187 - accuracy: 0.8400
Epoch 1258/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4869 - accuracy: 0.8000
Epoch 1259/2000
50/50 [==============================] - 0s 340us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.4150 - accuracy: 0.8400
Epoch 1329/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3702 - accuracy: 0.8600
Epoch 1330/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3671 - accuracy: 0.8600
Epoch 1331/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3693 - accuracy: 0.9000
Epoch 1332/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3726 - accuracy: 0.8800
Epoch 1333/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3615 - accuracy: 0.8800
Epoch 1334/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3918 - accuracy: 0.8200
Epoch 1335/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3721 - accuracy: 0.8800
Epoch 1336/2000
50/50 [==============================] - 0s 320us/step - loss: 0.4027 - accuracy: 0.8400
Epoch 1337/2000
50/50 [==============================] - 0s 340us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.3653 - accuracy: 0.8600
Epoch 1407/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3532 - accuracy: 0.8800
Epoch 1408/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3640 - accuracy: 0.8800
Epoch 1409/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3641 - accuracy: 0.8200
Epoch 1410/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3529 - accuracy: 0.8600
Epoch 1411/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3635 - accuracy: 0.8600
Epoch 1412/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3531 - accuracy: 0.8800
Epoch 1413/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3739 - accuracy: 0.8600
Epoch 1414/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3512 - accuracy: 0.8600
Epoch 1415/2000
50/50 [==============================] - 0s 480us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.3409 - accuracy: 0.8800
Epoch 1485/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3524 - accuracy: 0.8600
Epoch 1486/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3622 - accuracy: 0.8400
Epoch 1487/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3782 - accuracy: 0.8800
Epoch 1488/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3515 - accuracy: 0.8600
Epoch 1489/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3397 - accuracy: 0.8600
Epoch 1490/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3559 - accuracy: 0.8400
Epoch 1491/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3446 - accuracy: 0.8600
Epoch 1492/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3437 - accuracy: 0.8600
Epoch 1493/2000
50/50 [==============================] - 0s 320us/step 

50/50 [==============================] - 0s 320us/step - loss: 0.3293 - accuracy: 0.8600
Epoch 1562/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3715 - accuracy: 0.8400
Epoch 1563/2000
50/50 [==============================] - 0s 480us/step - loss: 0.3403 - accuracy: 0.8600
Epoch 1564/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3392 - accuracy: 0.8600
Epoch 1565/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3414 - accuracy: 0.8600
Epoch 1566/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3287 - accuracy: 0.8800
Epoch 1567/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3429 - accuracy: 0.8600
Epoch 1568/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3287 - accuracy: 0.8600
Epoch 1569/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3280 - accuracy: 0.8600
Epoch 1570/2000
50/50 [==============================] - 0s 320us/step 

50/50 [==============================] - 0s 300us/step - loss: 0.3540 - accuracy: 0.8600
Epoch 1639/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3209 - accuracy: 0.8800
Epoch 1640/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3729 - accuracy: 0.8400
Epoch 1641/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3295 - accuracy: 0.8200
Epoch 1642/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3232 - accuracy: 0.8800
Epoch 1643/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3265 - accuracy: 0.8800
Epoch 1644/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3299 - accuracy: 0.8800
Epoch 1645/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3167 - accuracy: 0.8600
Epoch 1646/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3324 - accuracy: 0.8600
Epoch 1647/2000
50/50 [==============================] - 0s 320us/step 

50/50 [==============================] - 0s 300us/step - loss: 0.3450 - accuracy: 0.8600
Epoch 1716/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3173 - accuracy: 0.8800
Epoch 1717/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3387 - accuracy: 0.8600
Epoch 1718/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3187 - accuracy: 0.8400
Epoch 1719/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3295 - accuracy: 0.9000
Epoch 1720/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3517 - accuracy: 0.8800
Epoch 1721/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3383 - accuracy: 0.8600
Epoch 1722/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3187 - accuracy: 0.8600
Epoch 1723/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3178 - accuracy: 0.8400
Epoch 1724/2000
50/50 [==============================] - 0s 340us/step 

50/50 [==============================] - 0s 340us/step - loss: 0.3040 - accuracy: 0.8400
Epoch 1794/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3031 - accuracy: 0.8800
Epoch 1795/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3053 - accuracy: 0.8800
Epoch 1796/2000
50/50 [==============================] - 0s 300us/step - loss: 0.2963 - accuracy: 0.8800
Epoch 1797/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3189 - accuracy: 0.8400
Epoch 1798/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2999 - accuracy: 0.8600
Epoch 1799/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3062 - accuracy: 0.8600
Epoch 1800/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3100 - accuracy: 0.8600
Epoch 1801/2000
50/50 [==============================] - 0s 300us/step - loss: 0.3014 - accuracy: 0.9000
Epoch 1802/2000
50/50 [==============================] - 0s 320us/step 

Epoch 1871/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2953 - accuracy: 0.8800
Epoch 1872/2000
50/50 [==============================] - 0s 300us/step - loss: 0.2972 - accuracy: 0.8600
Epoch 1873/2000
50/50 [==============================] - 0s 340us/step - loss: 0.3028 - accuracy: 0.8800
Epoch 1874/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2912 - accuracy: 0.8800
Epoch 1875/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3093 - accuracy: 0.8400
Epoch 1876/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3048 - accuracy: 0.8600
Epoch 1877/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2993 - accuracy: 0.8600
Epoch 1878/2000
50/50 [==============================] - 0s 300us/step - loss: 0.2983 - accuracy: 0.8600
Epoch 1879/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2932 - accuracy: 0.8800
Epoch 1880/2000
50/50 [==============================] 

50/50 [==============================] - 0s 300us/step - loss: 0.2940 - accuracy: 0.8600
Epoch 1949/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2879 - accuracy: 0.8600
Epoch 1950/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2927 - accuracy: 0.9000
Epoch 1951/2000
50/50 [==============================] - 0s 300us/step - loss: 0.2910 - accuracy: 0.8400
Epoch 1952/2000
50/50 [==============================] - 0s 340us/step - loss: 0.2866 - accuracy: 0.8800
Epoch 1953/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3190 - accuracy: 0.8600
Epoch 1954/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3116 - accuracy: 0.8800
Epoch 1955/2000
50/50 [==============================] - 0s 320us/step - loss: 0.3037 - accuracy: 0.8600
Epoch 1956/2000
50/50 [==============================] - 0s 320us/step - loss: 0.2976 - accuracy: 0.8600
Epoch 1957/2000
50/50 [==============================] - 0s 320us/step 

In [40]:
scores=model.evaluate(xTrain,yTrain)
print("%s:%.2f%%" %(model.metrics_names[1],scores[1]*100))

50/50 [==============================] - 0s 1ms/step
accuracy:86.00%


In [41]:
## 앞에 일반 신경망보다 lstm을 썻는데도 성능이 더 떨어졌다.
# 왜그럴까? stateful? 상태유지모드 적용되지 않았기 때문
"""
LSTM(메모리셀개수, input_dim=입력송성수, input_length=시퀀스데이터입력길이)
return_sequences : 시퀀스출력여부
False=마지막 시퀀스에서 한번만 출력(many to one)
True=각 시퀀스에서 출력(many to many)

-stateful:상태유지모드
학습 샘플의 가장 마지막 상태가 다음 샘플
학습할때 입력으로 전달할 것인지 여부

"""

'\nLSTM(메모리셀개수, input_dim=입력송성수, input_length=시퀀스데이터입력길이)\nreturn_sequences : 시퀀스출력여부\nFalse=마지막 시퀀스에서 한번만 출력(many to one)\nTrue=각 시퀀스에서 출력(many to many)\n\n-stateful:상태유지모드\n학습 샘플의 가장 마지막 상태가 다음 샘플\n학습할때 입력으로 전달할 것인지 여부\n\n'

In [42]:
"""
상태유지모드(stateful)에서 현재 샘플의 학습
상태가 다음 샘플의 초기 상태로 전달

LSTM 셀 내부적으로 기억할 것은 기억하고,
버릴 것은 버리도록 하기위한 옵션
stateful=True

상태유지모드에서는 입력형태를(batch_input_shape)
(배치사이즈, 타임스텝, 속성)으로 설정

"""

'\n상태유지모드(stateful)에서 현재 샘플의 학습\n상태가 다음 샘플의 초기 상태로 전달\n\nLSTM 셀 내부적으로 기억할 것은 기억하고,\n버릴 것은 버리도록 하기위한 옵션\nstateful=True\n\n상태유지모드에서는 입력형태를(batch_input_shape)\n(배치사이즈, 타임스텝, 속성)으로 설정\n\n'

In [43]:
model=Sequential()
model.add(LSTM(128, batch_input_shape=(1,4,1),stateful=True))
#128출력셀, 4타임스텝, 1 속성개수
#stateful=기본값이 False, 여기서는 True로 해주어야 함.
model.add(Dense(oneHotVecSize, activation='softmax'))

In [44]:
"""
-한 에폭안에서 여러개의 시퀀스 데이터가 있을때,
새로운 시퀀스 데이터를 학습하기 전에 상태 초기화 필요

-마지막 샘플 학습을 마치고나서, 새로운 에폭이
실행될때에는 새로운 샘플 학습을 해야하므로 상태 초기화가 필요

"""


'\n-한 에폭안에서 여러개의 시퀀스 데이터가 있을때,\n새로운 시퀀스 데이터를 학습하기 전에 상태 초기화 필요\n\n-마지막 샘플 학습을 마치고나서, 새로운 에폭이\n실행될때에는 새로운 샘플 학습을 해야하므로 상태 초기화가 필요\n\n'

In [45]:
#모델 학습과정
model.compile(loss="categorical_crossentropy",optimizer='adam',
             metrics=['accuracy'])

In [46]:
numEpochs=2000

In [47]:
for i in range(numEpochs):
    print("에폭:"+str(i))
    model.fit(xTrain,yTrain,epochs=1,batch_size=1,callbacks=[history],shuffle=False)
    model.reset_states()
    #state 정보를 초기화

에폭:0
Epoch 1/1
50/50 [==============================] - 0s 6ms/step - loss: 2.3673 - accuracy: 0.2200
에폭:1
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9893 - accuracy: 0.3400
에폭:2
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9543 - accuracy: 0.3400
에폭:3
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9407 - accuracy: 0.3400
에폭:4
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9323 - accuracy: 0.3400
에폭:5
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9261 - accuracy: 0.3400
에폭:6
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9211 - accuracy: 0.3400
에폭:7
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9170 - accuracy: 0.3400
에폭:8
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9134 - accuracy: 0.3400
에폭:9
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9101

50/50 [==============================] - 0s 2ms/step - loss: 1.3828 - accuracy: 0.5200
에폭:80
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4759 - accuracy: 0.4200
에폭:81
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2609 - accuracy: 0.4800
에폭:82
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2872 - accuracy: 0.5400
에폭:83
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2444 - accuracy: 0.5200
에폭:84
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.3554 - accuracy: 0.5000
에폭:85
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2180 - accuracy: 0.5400
에폭:86
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2560 - accuracy: 0.5600
에폭:87
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.3509 - accuracy: 0.5400
에폭:88
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.0904 - acc

50/50 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 0.8400
에폭:159
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.4580 - accuracy: 0.8400
에폭:160
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.3420 - accuracy: 0.9000
에폭:161
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.4330 - accuracy: 0.8400
에폭:162
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.2138 - accuracy: 0.9600
에폭:163
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.2218 - accuracy: 0.9600
에폭:164
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.2832 - accuracy: 0.9200
에폭:165
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.2441 - accuracy: 0.9200
에폭:166
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1651 - accuracy: 0.9800
에폭:167
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1

50/50 [==============================] - 0s 2ms/step - loss: 0.0028 - accuracy: 1.0000
에폭:237
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0027 - accuracy: 1.0000
에폭:238
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000
에폭:239
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000
에폭:240
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0024 - accuracy: 1.0000
에폭:241
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0023 - accuracy: 1.0000
에폭:242
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 1.0000
에폭:243
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 1.0000
에폭:244
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000
에폭:245
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0

50/50 [==============================] - 0s 2ms/step - loss: 0.0306 - accuracy: 1.0000
에폭:315
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0272 - accuracy: 1.0000
에폭:316
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0243 - accuracy: 1.0000
에폭:317
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0217 - accuracy: 1.0000
에폭:318
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0195 - accuracy: 1.0000
에폭:319
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0178 - accuracy: 1.0000
에폭:320
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0165 - accuracy: 1.0000
에폭:321
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0153 - accuracy: 1.0000
에폭:322
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0142 - accuracy: 1.0000
에폭:323
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0

50/50 [==============================] - 0s 2ms/step - loss: 7.0855e-04 - accuracy: 1.0000
에폭:393
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.8632e-04 - accuracy: 1.0000
에폭:394
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.6500e-04 - accuracy: 1.0000
에폭:395
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.4528e-04 - accuracy: 1.0000
에폭:396
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.2514e-04 - accuracy: 1.0000
에폭:397
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.0571e-04 - accuracy: 1.0000
에폭:398
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.8639e-04 - accuracy: 1.0000
에폭:399
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.6738e-04 - accuracy: 1.0000
에폭:400
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.4900e-04 - accuracy: 1.0000
에폭:401
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 7.9200e-05 - accuracy: 1.0000
에폭:468
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.6919e-05 - accuracy: 1.0000
에폭:469
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.4695e-05 - accuracy: 1.0000
에폭:470
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.2516e-05 - accuracy: 1.0000
에폭:471
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.0408e-05 - accuracy: 1.0000
에폭:472
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.8346e-05 - accuracy: 1.0000
에폭:473
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.6356e-05 - accuracy: 1.0000
에폭:474
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.4413e-05 - accuracy: 1.0000
에폭:475
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.2544e-05 - accuracy: 1.0000
에폭:476
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 1.0166e-05 - accuracy: 1.0000
에폭:543
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 9.8848e-06 - accuracy: 1.0000
에폭:544
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 9.6392e-06 - accuracy: 1.0000
에폭:545
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 9.3745e-06 - accuracy: 1.0000
에폭:546
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 9.1528e-06 - accuracy: 1.0000
에폭:547
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 8.8930e-06 - accuracy: 1.0000
에폭:548
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 8.6450e-06 - accuracy: 1.0000
에폭:549
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 8.4257e-06 - accuracy: 1.0000
에폭:550
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 8.2063e-06 - accuracy: 1.0000
에폭:551
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 0.0126 - accuracy: 1.0000
에폭:621
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0114 - accuracy: 1.0000
에폭:622
Epoch 1/1
50/50 [==============================] - ETA: 0s - loss: 0.0069 - accuracy: 1.0000   - 0s 2ms/step - loss: 0.0103 - accuracy: 1.0000
에폭:623
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0094 - accuracy: 1.0000
에폭:624
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0085 - accuracy: 1.0000
에폭:625
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0078 - accuracy: 1.0000
에폭:626
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0072 - accuracy: 1.0000
에폭:627
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0066 - accuracy: 1.0000
에폭:628
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0061 - accuracy: 1.0000
에폭:629
Epoch 1/1
50/50 [===========

50/50 [==============================] - 0s 2ms/step - loss: 4.7440e-04 - accuracy: 1.0000
에폭:698
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.5321e-04 - accuracy: 1.0000
에폭:699
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.3369e-04 - accuracy: 1.0000
에폭:700
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.1587e-04 - accuracy: 1.0000
에폭:701
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.9832e-04 - accuracy: 1.0000
에폭:702
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.8041e-04 - accuracy: 1.0000
에폭:703
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6301e-04 - accuracy: 1.0000
에폭:704
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.4732e-04 - accuracy: 1.0000
에폭:705
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.3385e-04 - accuracy: 1.0000
에폭:706
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 5.7521e-05 - accuracy: 1.0000
에폭:773
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.6193e-05 - accuracy: 1.0000
에폭:774
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.4894e-05 - accuracy: 1.0000
에폭:775
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.3625e-05 - accuracy: 1.0000
에폭:776
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.2381e-05 - accuracy: 1.0000
에폭:777
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 5.1156e-05 - accuracy: 1.0000
에폭:778
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.9954e-05 - accuracy: 1.0000
에폭:779
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.8788e-05 - accuracy: 1.0000
에폭:780
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.7639e-05 - accuracy: 1.0000
에폭:781
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 8.4662e-06 - accuracy: 1.0000
에폭:849
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 8.2540e-06 - accuracy: 1.0000
에폭:850
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 8.0633e-06 - accuracy: 1.0000
에폭:851
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.8630e-06 - accuracy: 1.0000
에폭:852
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.6627e-06 - accuracy: 1.0000
에폭:853
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.4815e-06 - accuracy: 1.0000
에폭:854
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.3146e-06 - accuracy: 1.0000
에폭:855
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.1334e-06 - accuracy: 1.0000
에폭:856
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 6.9785e-06 - accuracy: 1.0000
에폭:857
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 1.2541e-06 - accuracy: 1.0000
에폭:925
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2302e-06 - accuracy: 1.0000
에폭:926
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.1992e-06 - accuracy: 1.0000
에폭:927
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.1659e-06 - accuracy: 1.0000
에폭:928
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.1396e-06 - accuracy: 1.0000
에폭:929
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.1063e-06 - accuracy: 1.0000
에폭:930
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.0753e-06 - accuracy: 1.0000
에폭:931
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.0419e-06 - accuracy: 1.0000
에폭:932
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.0204e-06 - accuracy: 1.0000
에폭:933
Epoch 1/1
50/50 [=====================

50/50 [==============================] - 0s 2ms/step - loss: 1.6689e-07 - accuracy: 1.0000
에폭:1001
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.6451e-07 - accuracy: 1.0000
에폭:1002
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.6212e-07 - accuracy: 1.0000
에폭:1003
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.5497e-07 - accuracy: 1.0000
에폭:1004
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.5497e-07 - accuracy: 1.0000
에폭:1005
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4544e-07 - accuracy: 1.0000
에폭:1006
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4305e-07 - accuracy: 1.0000
에폭:1007
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4067e-07 - accuracy: 1.0000
에폭:1008
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2875e-07 - accuracy: 1.0000
에폭:1009
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 1.4305e-08 - accuracy: 1.0000
에폭:1076
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9073e-08 - accuracy: 1.0000
에폭:1077
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4305e-08 - accuracy: 1.0000
에폭:1078
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.6689e-08 - accuracy: 1.0000
에폭:1079
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.6689e-08 - accuracy: 1.0000
에폭:1080
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.6689e-08 - accuracy: 1.0000
에폭:1081
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9073e-08 - accuracy: 1.0000
에폭:1082
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4305e-08 - accuracy: 1.0000
에폭:1083
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.1921e-08 - accuracy: 1.0000
에폭:1084
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 0.0234 - accuracy: 1.0000
에폭:1153
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0204 - accuracy: 1.0000
에폭:1154
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0179 - accuracy: 1.0000
에폭:1155
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0158 - accuracy: 1.0000
에폭:1156
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0140 - accuracy: 1.0000
에폭:1157
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0125 - accuracy: 1.0000
에폭:1158
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0112 - accuracy: 1.0000
에폭:1159
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0101 - accuracy: 1.0000
에폭:1160
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0092 - accuracy: 1.0000
에폭:1161
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - 

50/50 [==============================] - 0s 2ms/step - loss: 3.6800e-04 - accuracy: 1.0000
에폭:1230
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6314e-04 - accuracy: 1.0000
에폭:1231
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6108e-04 - accuracy: 1.0000
에폭:1232
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6213e-04 - accuracy: 1.0000
에폭:1233
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6606e-04 - accuracy: 1.0000
에폭:1234
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.7152e-04 - accuracy: 1.0000
에폭:1235
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.7620e-04 - accuracy: 1.0000
에폭:1236
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.7768e-04 - accuracy: 1.0000
에폭:1237
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.7374e-04 - accuracy: 1.0000
에폭:1238
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 4.1226e-05 - accuracy: 1.0000
에폭:1305
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.0172e-05 - accuracy: 1.0000
에폭:1306
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.9125e-05 - accuracy: 1.0000
에폭:1307
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.8110e-05 - accuracy: 1.0000
에폭:1308
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.7104e-05 - accuracy: 1.0000
에폭:1309
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6152e-05 - accuracy: 1.0000
에폭:1310
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.5211e-05 - accuracy: 1.0000
에폭:1311
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.4286e-05 - accuracy: 1.0000
에폭:1312
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.3423e-05 - accuracy: 1.0000
에폭:1313
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 7.3146e-06 - accuracy: 1.0000
에폭:1380
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 7.1174e-04 - accuracy: 1.0000
에폭:1381
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.0623 - accuracy: 0.3800
에폭:1382
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.2312 - accuracy: 0.2200
에폭:1383
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.0154 - accuracy: 0.2200
에폭:1384
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.7096 - accuracy: 0.4200
에폭:1385
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.5352 - accuracy: 0.3600
에폭:1386
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4423 - accuracy: 0.4000
에폭:1387
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.3481 - accuracy: 0.4200
에폭:1388
Epoch 1/1
50/50 [==============================] - 0s 2ms

50/50 [==============================] - 0s 2ms/step - loss: 0.0082 - accuracy: 1.0000
에폭:1458
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 1.0000
에폭:1459
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 1.0000
에폭:1460
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 1.0000
에폭:1461
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1102 - accuracy: 0.9400
에폭:1462
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.0220 - accuracy: 0.7600
에폭:1463
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.6120 - accuracy: 0.8000
에폭:1464
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.8086 - accuracy: 0.7200
에폭:1465
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.8487 - accuracy: 0.7600
에폭:1466
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - 

50/50 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 1.0000
에폭:1536
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000
에폭:1537
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000
에폭:1538
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000
에폭:1539
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000
에폭:1540
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000
에폭:1541
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0014 - accuracy: 1.0000
에폭:1542
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0014 - accuracy: 1.0000
에폭:1543
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000
에폭:1544
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - 

50/50 [==============================] - 0s 2ms/step - loss: 1.5044e-04 - accuracy: 1.0000
에폭:1611
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4664e-04 - accuracy: 1.0000
에폭:1612
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.4299e-04 - accuracy: 1.0000
에폭:1613
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.3948e-04 - accuracy: 1.0000
에폭:1614
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.3608e-04 - accuracy: 1.0000
에폭:1615
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.3285e-04 - accuracy: 1.0000
에폭:1616
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2972e-04 - accuracy: 1.0000
에폭:1617
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2674e-04 - accuracy: 1.0000
에폭:1618
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.2388e-04 - accuracy: 1.0000
에폭:1619
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 2.2640e-05 - accuracy: 1.0000
에폭:1686
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.1913e-05 - accuracy: 1.0000
에폭:1687
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.1202e-05 - accuracy: 1.0000
에폭:1688
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.1162e-05 - accuracy: 1.0000
에폭:1689
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9934e-05 - accuracy: 1.0000
에폭:1690
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.9636e-05 - accuracy: 1.0000
에폭:1691
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.8627e-05 - accuracy: 1.0000
에폭:1692
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.8589e-05 - accuracy: 1.0000
에폭:1693
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 1.7445e-05 - accuracy: 1.0000
에폭:1694
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 3.0565e-06 - accuracy: 1.0000
에폭:1761
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.9826e-06 - accuracy: 1.0000
에폭:1762
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.9111e-06 - accuracy: 1.0000
에폭:1763
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.8396e-06 - accuracy: 1.0000
에폭:1764
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.7418e-06 - accuracy: 1.0000
에폭:1765
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.6822e-06 - accuracy: 1.0000
에폭:1766
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.5940e-06 - accuracy: 1.0000
에폭:1767
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.5248e-06 - accuracy: 1.0000
에폭:1768
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 2.4533e-06 - accuracy: 1.0000
에폭:1769
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 0.1971 - accuracy: 0.9200
에폭:1838
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1749 - accuracy: 0.9600
에폭:1839
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0704 - accuracy: 1.0000
에폭:1840
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.2321 - accuracy: 0.9400
에폭:1841
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.5963 - accuracy: 0.8000
에폭:1842
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.5368 - accuracy: 0.8000
에폭:1843
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.4880 - accuracy: 0.8400
에폭:1844
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1797 - accuracy: 0.9200
에폭:1845
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1299 - accuracy: 0.9600
에폭:1846
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - 

50/50 [==============================] - 0s 2ms/step - loss: 5.1171e-04 - accuracy: 1.0000
에폭:1915
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.8777e-04 - accuracy: 1.0000
에폭:1916
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.6569e-04 - accuracy: 1.0000
에폭:1917
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.4597e-04 - accuracy: 1.0000
에폭:1918
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.2949e-04 - accuracy: 1.0000
에폭:1919
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 4.1608e-04 - accuracy: 1.0000
에폭:1920
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.9980e-04 - accuracy: 1.0000
에폭:1921
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.8110e-04 - accuracy: 1.0000
에폭:1922
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 3.6534e-04 - accuracy: 1.0000
에폭:1923
Epoch 1/1
50/50 [============

50/50 [==============================] - 0s 2ms/step - loss: 0.8090 - accuracy: 0.7200
에폭:1991
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.4357 - accuracy: 0.8600
에폭:1992
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.3274 - accuracy: 0.8800
에폭:1993
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.2303 - accuracy: 0.9600
에폭:1994
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.1372 - accuracy: 0.9600
에폭:1995
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0863 - accuracy: 1.0000
에폭:1996
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0631 - accuracy: 1.0000
에폭:1997
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0476 - accuracy: 1.0000
에폭:1998
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - loss: 0.0369 - accuracy: 1.0000
에폭:1999
Epoch 1/1
50/50 [==============================] - 0s 2ms/step - 

In [48]:
model.evaluate(xTrain,yTrain,batch_size=1)
print("%s:%.2f%%" %(model.metrics_names[1],scores[1]*100))

50/50 [==============================] - 0s 2ms/step
accuracy:86.00%


In [49]:
#곡 전체 예측
seqIn=['g8','e8','e4','f8']
seqOut=seqIn
seqIn=[code2idx[it]/float(maxIdxValue) for it in seqIn]
print(np.shape(seqIn))

(4,)


In [50]:
seqOut=['g8','e8','e4','f8']
predOut=model.predict(xTrain,batch_size=1)
predCount=50
for i in range(predCount):
    idx=np.argmax(predOut[i])
    seqOut.append(idx2code[idx])
print(seqOut)

['g8', 'e8', 'e4', 'f8', 'd8', 'd8', 'd8', 'd8', 'g8', 'g8', 'e8', 'e8', 'e4', 'd8', 'd8', 'd8', 'd8', 'd8', 'f8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4', 'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4', 'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']


In [51]:
model.reset_states()

In [52]:
#곡 전체 예측
seqIn=['g8','e8','e4','f8']
seqOut=seqIn
seqIn=[code2idx[it]/float(maxIdxValue) for it in seqIn]

for i in range(predCount):
    seqIn2=np.array(seqIn)#[0.13,...]
    seqIn2=np.reshape(seqIn2,(1,4,1))#샘플수, 타임스텝수,속성수
    model.predict(seqIn2)
    predOut=model.predict(seqIn2)
    idx=np.argmax(predOut)
    seqOut.append(idx2code[idx])
    seqIn.append(idx/float(maxIdxValue))
    seqIn.pop(0)
print(seqOut)

['g8', 'e8', 'e4', 'f8', 'e8', 'd4', 'c8', 'e8', 'd4', 'c8', 'e8', 'e8', 'g8', 'e8', 'd8', 'e8', 'd8', 'e8', 'e4', 'f8', 'e8', 'd4', 'c8', 'e8', 'd4', 'c8', 'e8', 'g8', 'e8', 'e8', 'd8', 'e4', 'c8', 'e8', 'g8', 'e8', 'e8', 'd8', 'e4', 'c8', 'd8', 'g8', 'e8', 'e8', 'd8', 'e4', 'c8', 'e8', 'g8', 'e8', 'e8', 'd8', 'e4', 'c8']
